import test from "node:test";
import assert from "node:assert/strict";
import "../perfume-bundle.js";
import "../fragrance-finder-engine.js";

const product=(id,overrides={})=>({id,status:"published",category:"perfume",nameAr:id,nameEn:id,brand:"Fixture",gender:"unisex",images:[{url:`/${id}.webp`}],inventory:{quantity:3},accordProfile:[],noteSelectionsBundle:{top:[],heart:[],base:[]},seasonScores:{winter:null,autumn:null,spring:null,summer:null},usageTimeScores:{day:null,night:null},occasions:[],performance:{},...overrides});
const warm=product("A",{accordProfile:[{nameAr:"فانيليا",nameEn:"Vanilla",strength:95},{nameAr:"خشبي",nameEn:"Woody",strength:85}],noteSelectionsBundle:{top:[],heart:[{ar:"قرفة",en:"Cinnamon"}],base:[{ar:"فانيليا",en:"Vanilla"}]},families:["Oriental"],seasonScores:{winter:100,autumn:100,spring:40,summer:0},usageTimeScores:{day:40,night:100},performance:{longevity:11,projection:"strong"}});
const fresh=product("B",{accordProfile:[{nameAr:"حمضي",nameEn:"Citrus",strength:96},{nameAr:"منعش",nameEn:"Fresh",strength:90}],noteSelectionsBundle:{top:[{ar:"برغموت",en:"Bergamot"},{ar:"ليمون",en:"Lemon"}],heart:[],base:[]},families:["Citrus"],seasonScores:{winter:0,autumn:20,spring:80,summer:100},usageTimeScores:{day:100,night:20},performance:{longevity:5,projection:"moderate"}});
const floral=product("C",{accordProfile:[{nameAr:"زهري",nameEn:"Floral",strength:70}],noteSelectionsBundle:{top:[],heart:[{ar:"ورد",en:"Rose"}],base:[]},families:["Floral"],seasonScores:{winter:40,autumn:60,spring:100,summer:60},usageTimeScores:{day:80,night:60},performance:{longevity:null,projection:"moderate"}});
const engine=globalThis.ORIGOFragranceFinderEngine;

test("season and time scores change ranking",()=>{assert.equal(engine.rankProducts([fresh,floral,warm],{seasons:["winter"]})[0].profile.id,"A");assert.equal(engine.rankProducts([warm,floral,fresh],{seasons:["summer"]})[0].profile.id,"B");assert.equal(engine.rankProducts([fresh,warm],{times:["night"]})[0].profile.id,"A");assert.equal(engine.rankProducts([warm,fresh],{times:["day"]})[0].profile.id,"B")});
test("finder uses the full percentage instead of a selected threshold",()=>{const high=product("100",{seasonScores:{winter:100,autumn:null,spring:null,summer:null}}),medium=product("70",{seasonScores:{winter:70,autumn:null,spring:null,summer:null}}),low=product("30",{seasonScores:{winter:30,autumn:null,spring:null,summer:null}});const ranked=engine.rankProducts([low,high,medium],{seasons:["winter"]});assert.deepEqual(ranked.map((item)=>item.profile.id),["100","70","30"]);assert.ok(ranked[0].score>ranked[1].score&&ranked[1].score>ranked[2].score)});
test("accord strength and custom accords affect scores without using notes",()=>{const low=product("low",{accordProfile:[{nameEn:"Mineral Rain",strength:30}],noteSelectionsBundle:{top:[{ar:"ليمون",en:"Lemon"}]}});const high=product("high",{accordProfile:[{nameEn:"Mineral Rain",strength:95}]});assert.ok(engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(high),{accords:["Mineral Rain"]}).score>engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(low),{accords:["Mineral Rain"]}).score);assert.equal("notes" in engine.buildFinderProfileFromProduct(low),false);assert.equal(engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(low),{likedNotes:["Lemon"]}).availableWeight,0)});
test("custom occasions and scent character participate without outweighing accords",()=>{const matching=product("matching",{occasions:["Evening events"],occasionLabels:[{ar:"السهرات",en:"Evening events"}],scentCharacterAr:["دافئ"],scentCharacterEn:["Warm"]}),plain=product("plain");assert.ok(engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(matching),{occasions:["السهرات"],scentCharacter:["Warm"]}).score>engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(plain),{occasions:["السهرات"],scentCharacter:["Warm"]}).score);assert.ok(engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(warm),{accords:["Vanilla"]}).availableWeight>engine.scoreFinderProfile(engine.buildFinderProfileFromProduct(matching),{scentCharacter:["Warm"]}).availableWeight)});
test("longevity, sillage and missing values are handled without invented zeroes",()=>{assert.equal(engine.rankProducts([fresh,warm],{longevity:"long"})[0].profile.id,"A");assert.equal(engine.rankProducts([fresh,warm],{sillage:"strong"})[0].profile.id,"A");const profile=engine.buildFinderProfileFromProduct(floral);assert.equal(profile.longevity,null);assert.doesNotThrow(()=>engine.scoreFinderProfile(profile,{longevity:"long"}))});
test("saved products and newly imported ORIGO bundles work without finder records",()=>{const canonical={perfume:{name_ar:"جديد",name_en:"New",brand_ar:"علامة",brand_en:"Brand",gender_ar:"للجنسين",gender_en:"Unisex",concentration_ar:"",concentration_en:"",concentration_code:"EDP",size_ml:100,release_year:null,fragrance_family_ar:"شرقي",fragrance_family_en:"Oriental",accords:[{name_ar:"مخصص",name_en:"Custom Glow",percentage:88}],notes:{top:[{name_ar:"هيل",name_en:"Cardamom"}],heart:[],base:[]},performance:{longevity_ar:"",longevity_en:"",longevity_hours:null,projection_ar:"",projection_en:""},seasons:{winter:80,autumn:null,spring:null,summer:null},time:{day:null,night:100},occasions:[],short_description_ar:"",short_description_en:"",scent_character_ar:[],scent_character_en:[],search_keywords_ar:[],search_keywords_en:[]}};const saved=globalThis.ORIGOPerfumeBundle.applyPerfumeBundleToProduct(product("new"),canonical);const profile=engine.buildFinderProfileFromProduct(saved);assert.equal(profile.accords[0].en,"Custom Glow");assert.equal("notes" in profile,false);assert.equal(profile.image,"/new.webp")});
test("editing product percentage invalidates cached profile and changes score",()=>{engine.clearCache();const editable=structuredClone(warm);const before=engine.rankProducts([editable],{seasons:["winter"]})[0].score;editable.seasonScores.winter=30;const after=engine.rankProducts([editable],{seasons:["winter"]})[0].score;assert.ok(after<before)});
