import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";

const source=await readFile(new URL("../app.js",import.meta.url),"utf8");
const html=await readFile(new URL("../index.html",import.meta.url),"utf8");
const activeEditor=source.slice(source.indexOf("function renderImportReview(product)"),source.indexOf("function optionValuesForProduct"));
const importAction=source.slice(source.indexOf('if (action === "parse-perfume-bundle")'),source.indexOf('if (action === "clear-perfume-bundle")'));

test("the perfume-name research workflow is absent from the product editor",()=>{assert.doesNotMatch(html,/id="web-product-query"|id="web-import-form"|Dior Sauvage|بحث شامل/);assert.doesNotMatch(source,/\$\("#web-product-query"\)\.addEventListener/)});
test("the five gates expose only import, review, images and manual content",()=>{for(const number of [1,2,3,4,5])assert.match(activeEditor,new RegExp(`productEditorGate\\(${number}`));assert.match(source,/data-action="parse-perfume-bundle"/);assert.match(source,/data-action="export-perfume-bundle"/);assert.match(activeEditor,/name="releaseYear"/);assert.match(activeEditor,/name:"families"/)});
test("active editor contains no perfume generation or suggestion controls",()=>{const forbidden=["سيولده النظام تلقائيًا","سيولد النظام تلقائيًا","اضغط زر التوليد","توليد المواسم والأوقات والمناسبات","اقتراح المناسبات","تحديث الاقتراحات تلقائيًا","نتائج محسوبة عند الحفظ","generate-product-seo","generate-perfume-usage"];for(const phrase of forbidden)assert.doesNotMatch(activeEditor,new RegExp(phrase))});
test("import applies normalized product and does not touch images or commerce directly",()=>{assert.match(importAction,/applyPerfumeBundleToProduct\(current, normalized\)/);assert.doesNotMatch(importAction,/price|quantity|images\s*=/);assert.match(importAction,/state\.activeImportDraft = merged/)});
test("canonical gender replaces stale smart-select gender state",()=>{assert.match(importAction,/merged\.genders = normalized\.perfume\.gender \? \[normalized\.perfume\.gender\] : \[\]/);assert.match(activeEditor,/Array\.isArray\(product\.genders\) && product\.genders\.length \? product\.genders : product\.gender/)});
test("rating and review count bind separately without fabricating missing values",()=>{assert.match(source,/name="overallRating"[\s\S]{0,120}step="0\.01"|step="0\.01"[\s\S]{0,120}name="overallRating"/);assert.match(source,/name="reviewCount"/);assert.match(source,/data\.get\("overallRating"\) === "" \? \(base\.rating \?\? null\)/);assert.match(source,/data\.get\("reviewCount"\) === "" \? \{\}/)});
test("bilingual SEO renders the active language and retains both model values",()=>{assert.match(activeEditor,/localizedText\(product\.seo\?\.titleAr, product\.seo\?\.titleEn\)/);assert.match(source,/seo\[`title\$\{suffix\}`\]/);assert.match(source,/keywordsAr/);assert.match(source,/keywordsEn/)});
test("canonical and robots SEO fields import and persist",()=>{assert.match(activeEditor,/name="seoCanonical"/);assert.match(activeEditor,/name="seoRobots"/);assert.match(source,/setField\("seoCanonical", imported\.seo\?\.canonical\)/);assert.match(source,/seo\.canonical = String\(data\.get\("seoCanonical"\)/)});
test("bundle occasions register their bilingual labels before the editor rerenders",()=>{assert.match(importAction,/normalized\.occasions\.forEach/);assert.match(importAction,/nameAr:occasion\.ar \|\| occasion\.en/);assert.match(importAction,/nameEn:occasion\.en \|\| occasion\.ar/)});
test("editor number values use the Latin-digit normalization layer",()=>{assert.match(source,/normalizeLatinDigits\(product\.reviewSummary\?\.average/);assert.match(source,/normalizeLatinDigits\(product\.reviewSummary\?\.count/);assert.match(source,/new Intl\.NumberFormat\("en-US", \{ numberingSystem:"latn"/);assert.match(source,/MutationObserver/)});
test("saved reviewer count uses only reviewSummary.count",()=>{assert.match(source,/reviewSummary:\s*\{[\s\S]*data\.get\("reviewCount"\)[\s\S]*count:/);assert.doesNotMatch(activeEditor,/review_count|ratingVotes|reviewTotal/)});
test("imported occasions render in the active language and preserve structured labels",()=>{assert.match(source,/const name = localizedText\(item\.nameAr, item\.nameEn\) \|\| value/);assert.match(source,/occasionLabels: data\.has\("occasions"\) \? occasionSelections\.map/);assert.match(activeEditor,/product\.occasionLabels \|\| \[\]/)});
test("note smart selects replace failed artwork with a local fallback icon",()=>{assert.match(source,/data-smart-note-image="true"/);assert.match(source,/image\.dataset\.smartNoteImage === "true"/);assert.match(source,/fallback\.textContent = "✿"/)});
test("season and time percentages use responsive sliders",()=>{assert.match(source,/data-percentage-slider/);assert.match(source,/name:`seasonScore\.\$\{id\}`/);assert.match(source,/name:`usageScore\.\$\{id\}`/);assert.match(source,/name="\$\{name\}" min="0" max="100"/);assert.match(source,/Math\.min\(100, Number\(data\.get\(name\)\)\)/);assert.doesNotMatch(activeEditor,/0 إلى 5|0 to 5/)});
test("SKU, slug, description and SEO are not auto-generated by active preview",()=>{const preview=source.slice(source.indexOf("function updateProductEditorPreview"),source.indexOf("const ORIGO_ACCORD_LIBRARY"));assert.doesNotMatch(preview,/skuField|slugField|autoGenerated/);assert.doesNotMatch(activeEditor,/updateGeneratedProductSeo/)});
test("images remain a separate multi-image workflow",()=>{assert.match(activeEditor,/multiple/);assert.match(activeEditor,/productMediaStudioMarkup\(images\)/);assert.match(source,/normalizeProductImages\(base\.images \|\| \[\]\)/)});
test("save actions use a direct guarded click path and retain submit fallback",()=>{assert.match(activeEditor,/data-action="save-catalog-product"/);assert.match(source,/async function safelySaveCatalogProduct/);assert.match(source,/action === "save-catalog-product"/);assert.match(source,/event\.target\.id === "import-review-form"\) await safelySaveCatalogProduct/)});
test("image workflow preserves identity, ordering, main image and touch drag",()=>{const normalize=source.slice(source.indexOf("function normalizeProductImages"),source.indexOf("function setAdminStudioImage"));assert.match(normalize,/String\(item\.id \|\| url\)/);assert.match(normalize,/seen\.has\(key\) \|\| seen\.has\(url\)/);assert.match(normalize,/position:index, sortOrder:index, selected:index === 0/);assert.match(source,/data-action="admin-studio-main"/);assert.match(source,/data-action="admin-studio-delete"/);assert.match(source,/window\.confirm/);assert.match(source,/document\.addEventListener\("dragstart"/);assert.match(source,/document\.addEventListener\("pointerdown"/);assert.match(source,/draft\.images\.splice\(index, 1\)/)});
