import test from "node:test";
import assert from "node:assert/strict";
import {buildBreadcrumbStructuredData,buildCanonicalUrl,buildCategorySeo,buildImageAlt,buildProductSeo,buildProductStructuredData,buildSitemap,injectSeoIntoHtml,robotsTxt,seoForRoute} from "../seo.mjs";

const product={id:"p1",slug:"asad-bourbon",status:"published",category:"perfume",nameAr:"أسد بوربون",nameEn:"Asad Bourbon",brandAr:"لطافة",brandEn:"Lattafa",brand:"Lattafa",size:"100 ml",concentration:"EDP",price:1500,sku:"ASAD-100",barcode:"1234567890123",inventory:{quantity:2},images:[{url:"/asad.webp"}],seasonScores:{winter:100,summer:25},usageTimeScores:{day:60,night:100},gender:"men",updatedAt:"2026-08-21T00:00:00Z",reviewSummary:{average:4.5,count:3}};

test("product SEO is unique, deterministic and manual values win",()=>{const fallback=buildProductSeo(product);assert.match(fallback.title,/أسد بوربون/);assert.match(fallback.title,/لطافة/);assert.equal(fallback.canonical,"https://origoscents.com/perfume/asad-bourbon");const manual=buildProductSeo({...product,seo:{title:"Manual title",description:"Manual description"}});assert.equal(manual.title,"Manual title");assert.equal(manual.description,"Manual description")});
test("canonical URLs discard queries and duplicate metadata is removed",()=>{assert.equal(buildCanonicalUrl("/perfumes/winter?sort=price"),"https://origoscents.com/perfumes/winter");const html=injectSeoIntoHtml('<html><head><title>Old</title><meta name="description" content="old"><link rel="canonical" href="old"><meta property="og:title" content="old"></head></html>',seoForRoute("/perfume/asad-bourbon",[product]));assert.equal((html.match(/rel="canonical"/g)||[]).length,1);assert.match(html,/name="robots" content="index,follow"/)});
test("Product and Breadcrumb JSON-LD use real commerce data",()=>{const data=buildProductStructuredData(product);assert.equal(data.offers.priceCurrency,"EGP");assert.match(data.offers.availability,/InStock$/);assert.equal(data.brand.name,"لطافة");assert.equal(data.gtin,product.barcode);assert.equal(data.aggregateRating.reviewCount,3);assert.equal(buildProductStructuredData({...product,barcode:""}).gtin,undefined);const crumbs=buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطر",path:"/perfume/asad-bourbon"}]);assert.equal(crumbs["@type"],"BreadcrumbList");assert.equal(crumbs.itemListElement.length,2)});
test("brand, category and image helpers are dynamic",()=>{const category=buildCategorySeo("winter","عطور شتوية",1);assert.equal(category.robots,"index,follow");assert.match(category.title,/شتوية/);assert.equal(buildImageAlt(product),"عطر أسد بوربون من لطافة");assert.match(buildImageAlt(product,"en"),/Asad Bourbon by Lattafa/)});
test("sitemap includes published URLs and excludes drafts and private routes",()=>{const xml=buildSitemap([product,{...product,id:"draft",slug:"draft",status:"draft"}]);assert.match(xml,/perfume\/asad-bourbon/);assert.doesNotMatch(xml,/perfume\/draft|admin|account|checkout/);assert.match(xml,/perfumes\/winter/)});
test("search and personal finder results are noindex",()=>{assert.equal(seoForRoute("/search",[product]).robots,"noindex,follow");assert.equal(seoForRoute("/fragrance-finder/results",[product]).robots,"noindex,follow");assert.match(robotsTxt(),/Sitemap: https:\/\/origoscents\.com\/sitemap\.xml/)});
