(function(g){"use strict";const answers={gender:"any",accords:[],likedNotes:[],rejectedNotes:[],families:[],scentCharacter:[],seasons:[],times:[],occasions:[],longevity:"",sillage:""};let step=0;const t=k=>g.ORIGOFragranceFinderI18n.translate(document.documentElement.lang?.startsWith("en")?"en":"ar",k),esc=v=>g.ORIGOStore?.escapeHTML?.(String(v??""))||String(v??"").replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"})[m]),label=(ar,en)=>document.documentElement.lang?.startsWith("en")?en:ar;
function products(){return g.ORIGOStore?.state?.products||[]}function profiles(){return g.ORIGOFragranceFinderEngine.profilesFromProducts(products())}function options(field){const values=[];for(const profile of profiles()){if(field==="accords")profile.accords.forEach(v=>values.push(v.en||v.ar));if(["likedNotes","rejectedNotes"].includes(field))Object.values(profile.notes).flat().forEach(v=>values.push(v.en||v.ar));if(field==="families")values.push(...profile.families);if(field==="scentCharacter")values.push(...profile.scentCharacter);if(field==="occasions")values.push(...profile.occasions)}return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b)).slice(0,80)}
function chips(name,values){return`<div class="finder-chips">${values.map(value=>`<button type="button" data-finder-value="${esc(value)}" data-finder-name="${name}" class="${answers[name]?.includes(value)||answers[name.replace("Choice","")]===value?"selected":""}">${esc(value)}</button>`).join("")}</div>`}
function question(){if(step===0)return`<h2>${t("gender")}</h2>${chips("genderChoice",["men","women","unisex","any"])}`;if(step===1)return`<h2>${t("accords")}</h2>${chips("accords",options("accords"))}<h3>${label("العائلة العطرية","Fragrance family")}</h3>${chips("families",options("families"))}<h3>${label("طابع الرائحة","Scent character")}</h3>${chips("scentCharacter",options("scentCharacter"))}`;if(step===2)return`<h2>${t("notes")}</h2><h3>${label("أحبها","I like")}</h3>${chips("likedNotes",options("likedNotes"))}<h3>${label("لا أريدها","I do not want")}</h3>${chips("rejectedNotes",options("rejectedNotes"))}`;if(step===3)return`<h2>${t("season")}</h2>${chips("seasons",["winter","autumn","spring","summer"])}${chips("times",["day","night"])}<h3>${label("المناسبة","Occasion")}</h3>${chips("occasions",options("occasions"))}`;return`<h2>${t("performance")}</h2>${chips("longevityChoice",["long"])}${chips("sillageChoice",["strong"])}`}
function reason(item){const r=item.reasons[0],percent=(value)=>g.ORIGOStore.formatPercent(value);if(!r)return percent(item.score);if(r.type==="accords")return`${t("accords")}: ${r.values.slice(0,2).join("، ")}`;if(r.type==="notes")return`${t("notes")}: ${r.values.slice(0,2).join("، ")}`;if(r.type==="scentCharacter")return`${label("طابع الرائحة","Scent character")}: ${r.values.slice(0,2).join("، ")}`;if(r.type==="season")return`${t(r.value)} ${percent(r.score)}`;if(r.type==="time")return`${t(r.value)} ${percent(r.score)}`;if(r.type==="longevity")return`${g.ORIGOStore.formatNumber(r.hours)} h`;return percent(item.score)}
function results(){const ranked=g.ORIGOFragranceFinderEngine.rankProducts(products(),answers,6);return`<header><small>ORIGO MATCH</small><h1>${t("results")}</h1></header><div class="finder-results">${ranked.length?ranked.map(item=>{const p=item.profile;return`<article><img src="${esc(p.image)}" alt=""/><div><b>${esc(document.documentElement.lang?.startsWith("en")?p.nameEn||p.nameAr:p.nameAr||p.nameEn)}</b><small>${esc(p.brand)}</small><strong>${g.ORIGOStore.formatPercent(item.score)}</strong><p>${esc(reason(item))}</p><span>${t(p.available?"available":"unavailable")}${p.price!=null?` · ${g.ORIGOStore.formatPrice(p.price)}`:""}</span><button type="button" data-finder-product="${esc(p.id)}">${t("open")}</button></div></article>`}).join(""):`<p>${t("noResults")}</p>`}</div><button type="button" class="finder-restart" data-finder-restart>${t("restart")}</button>`}
function render(){const root=document.querySelector("#fragrance-finder-root");if(!root)return;root.innerHTML=step>4?results():`<header><small>${step+1} / 5</small><h1>${t("title")}</h1><p>${t("intro")}</p><progress value="${step+1}" max="5"></progress></header><section>${question()}</section><footer>${step?`<button type="button" data-finder-back>${t("back")}</button>`:""}<button type="button" data-finder-next>${t("next")}</button></footer>`}
function open(){document.querySelectorAll("#home,#commerce-page,#account-page,#alternatives-page").forEach(el=>{if(el)el.hidden=true});const page=document.querySelector("#fragrance-finder-page");if(page)page.hidden=false;history.pushState({},"","/fragrance-finder/for-whom");render();scrollTo({top:0,behavior:"smooth"})}
document.addEventListener("click",event=>{const button=event.target.closest("[data-finder-value],[data-finder-next],[data-finder-back],[data-finder-restart],[data-finder-product]");if(!button)return;if(button.dataset.finderValue!=null){const name=button.dataset.finderName,value=button.dataset.finderValue;if(name.endsWith("Choice")){const target=name.replace("Choice","");answers[target]=value;button.parentElement.querySelectorAll("button").forEach(b=>b.classList.toggle("selected",b===button))}else{const list=answers[name],index=list.indexOf(value);index>=0?list.splice(index,1):list.push(value);button.classList.toggle("selected")}return}if(button.hasAttribute("data-finder-next")){step++;render()}if(button.hasAttribute("data-finder-back")){step=Math.max(0,step-1);render()}if(button.hasAttribute("data-finder-restart")){step=0;render()}if(button.dataset.finderProduct){g.ORIGOStore.showProductDetails(g.ORIGOStore.getProduct(button.dataset.finderProduct))}});
g.ORIGOFragranceFinder={open,render,get answers(){return structuredClone(answers)}};
})(window);
