const SITE_URL="https://origoscents.com";
const SITE_NAME="ORIGO Scents";
const BRAND_ALTERNATE_NAMES=["ORIGO","Origo Scents","أوريجو سينتس","اوريجو سينتس","أوريجو","اوريجو"];
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const slug=value=>String(value??"").normalize("NFKD").toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"");
const list=value=>Array.isArray(value)?value:[];
const published=products=>list(products).filter(product=>product?.status==="published"&&product.deleted!==true&&(product.category||"perfume")==="perfume");
const brandNames=product=>[...new Set([product?.brandAr,product?.brandEn,product?.brand].map(value=>String(value||"").trim()).filter(Boolean))];
const brandSlug=product=>slug(product?.brandEn||product?.brand||product?.brandAr);
const brandRouteMatches=(product,wanted)=>brandNames(product).some(name=>slug(name)===wanted)||brandSlug(product)===wanted;
const money=value=>new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:2}).format(Number(value)||0);
const productName=product=>product?.nameAr||product?.nameEn||"";
const productBrand=product=>product?.brandAr||product?.brandEn||product?.brand||"";
const imageUrl=product=>list(product?.images).map(item=>typeof item==="string"?item:item?.url).find(Boolean)||product?.image||"";
const availableProduct=product=>product?.status!=="unavailable"&&(product?.inventory?.quantity==null||Number(product.inventory.quantity)>0);
const values=value=>Array.isArray(value)?value:value&&typeof value==="object"?[]:String(value||"").split(/[,،|]/).map(item=>item.trim()).filter(Boolean);

export function productPath(product){return `/perfume/${encodeURIComponent(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||product.id)}`}
export function buildCanonicalUrl(pathname="/"){const clean=`/${String(pathname).split("?")[0].replace(/^\/+|\/+$/g,"")}`;return `${SITE_URL}${clean==="/"?"/":clean}`}
export function buildImageAlt(product,language="ar"){return language==="ar"?`عطر ${product.nameAr||product.nameEn} من ${product.brandAr||product.brandEn||product.brand}`:`${product.nameEn||product.nameAr} by ${product.brandEn||product.brandAr||product.brand} perfume`}

export function buildProductSeo(product,language="ar"){
  const ar=language==="ar",name=ar?product.nameAr||product.nameEn:product.nameEn||product.nameAr,secondName=ar?product.nameEn:product.nameAr,brand=ar?product.brandAr||product.brandEn||product.brand:product.brandEn||product.brandAr||product.brand,size=product.size||product.sizes?.[0]||"",concentration=product.concentration||"",manual=product.seo||{};
  const bilingualName=secondName&&secondName!==name?`${name} | ${secondName}`:name;
  const fallbackTitle=ar?`${bilingualName} من ${brand}${size?` ${size}`:""} | عطر أصلي في مصر | ORIGO Scents`:`${brand} ${bilingualName}${size?` ${size}`:""} Original Perfume Egypt | ORIGO Scents`;
  const fallbackDescription=ar?`تسوق عطر ${name} الأصلي من ${brand} في مصر${size?`، ${size}`:""}${concentration?`، ${concentration}`:""}. تعرف على النوتات والثبات والفوحان والسعر والتوفر لدى ORIGO Scents.`:`Shop original ${name} by ${brand} in Egypt${size?`, ${size}`:""}${concentration?`, ${concentration}`:""}. Explore notes, longevity, projection, price and availability at ORIGO Scents.`;
  const image=list(product.images).map(item=>typeof item==="string"?item:item?.url).find(Boolean);
  return Object.freeze({title:manual.title||fallbackTitle,description:manual.description||(ar?product.descriptionAr:product.descriptionEn)||fallbackDescription,canonical:buildCanonicalUrl(productPath(product)),robots:"index,follow",keywords:list(manual.keywords),image:image?new URL(image,SITE_URL).href:"",imageAlt:buildImageAlt(product,language)});
}

export function buildProductStructuredData(product){
  const seo=buildProductSeo(product),quantity=product.inventory?.quantity,available=product.status!=="unavailable"&&(quantity==null||Number(quantity)>0),images=list(product.images).map(image=>typeof image==="string"?image:image?.url).filter(Boolean).map(url=>new URL(url,SITE_URL).href),names=[...new Set([product.nameAr,product.nameEn].filter(Boolean))];
  const data={"@context":"https://schema.org","@type":"Product",name:names.join(" | "),description:seo.description,image:images,sku:product.sku||undefined,brand:{"@type":"Brand",name:product.brandAr||product.brandEn||product.brand},offers:{"@type":"Offer",url:seo.canonical,priceCurrency:"EGP",price:Number(product.price),availability:`https://schema.org/${available?"InStock":"OutOfStock"}`,itemCondition:"https://schema.org/NewCondition"},url:seo.canonical};
  if(/^\d{8,14}$/.test(String(product.barcode||"")))data.gtin=String(product.barcode);
  const rating=Number(product.reviewSummary?.average??product.rating),count=Number(product.reviewSummary?.count);if(rating>0&&rating<=5&&count>0)data.aggregateRating={"@type":"AggregateRating",ratingValue:rating,reviewCount:count};return data;
}

export function buildBreadcrumbStructuredData(items){return{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:buildCanonicalUrl(item.path)}))}}
export function buildHomepageStructuredData(){return[
  {"@context":"https://schema.org","@type":"WebSite","@id":`${SITE_URL}/#website`,url:`${SITE_URL}/`,name:SITE_NAME,alternateName:BRAND_ALTERNATE_NAMES,inLanguage:["ar-EG","en-EG"],publisher:{"@id":`${SITE_URL}/#organization`}},
  {"@context":"https://schema.org","@type":"Organization","@id":`${SITE_URL}/#organization`,url:`${SITE_URL}/`,name:SITE_NAME,alternateName:BRAND_ALTERNATE_NAMES,logo:{"@type":"ImageObject",url:`${SITE_URL}/assets/origo-logo.svg`},areaServed:{"@type":"Country",name:"Egypt"}}
]}
export function buildBrandSeo(brand,count,path=""){
  const ar=String(brand?.ar||brand?.nameAr||"").trim(),en=String(brand?.en||brand?.nameEn||brand?.name||brand||"").trim(),primary=ar||en,secondary=ar&&en&&ar!==en?en:"";
  const title=secondary?`عطور ${primary} الأصلية | ${secondary} Perfumes Egypt | ORIGO Scents`:`عطور ${primary} الأصلية في مصر | ORIGO Scents`;
  const savedDescription=String(brand?.descriptionAr||brand?.descriptionEn||brand?.description||"").trim();
  return{title,description:savedDescription||`تسوق عطور ${primary} الأصلية في مصر من ORIGO Scents. اكتشف ${count} ${count===1?"منتج":"منتجات"} متوفرة مع الأسعار وبيانات العطر وخيارات التوصيل.`,canonical:buildCanonicalUrl(path||`/brands/${slug(en||primary)}`),robots:count?"index,follow":"noindex,follow"};
}
export function buildCategorySeo(type,label,count){return{title:`${label} في مصر | ORIGO Scents`,description:`اكتشف ${label} المتوفرة فعليًا لدى ORIGO Scents مع الأسعار وبيانات العطر والتوصيل داخل مصر.`,canonical:buildCanonicalUrl(`/perfumes/${type}`),robots:count?"index,follow":"noindex,follow"}}
function productByPath(products,path){const wanted=decodeURIComponent(path.split("/").filter(Boolean)[1]||"");return published(products).find(product=>(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||String(product.id))===wanted)}
export function findProductForPath(products,path){return productByPath(products,path)}

export function seoForRoute(pathname,products=[]){
  const items=published(products),path=String(pathname||"/").replace(/\/$/,"")||"/";
  if(["/search","/admin","/account","/checkout","/cart"].some(route=>path.startsWith(route))||path.startsWith("/fragrance-finder/results"))return{title:SITE_NAME,description:"",canonical:buildCanonicalUrl(path.startsWith("/search")?"/perfumes":path.startsWith("/fragrance-finder/results")?"/fragrance-finder/for-whom":path),robots:"noindex,follow",jsonLd:[]};
  if(path==="/")return{title:"ORIGO Scents | أوريجو سينتس - عطور أصلية 100% في مصر",description:"اكتشف ORIGO Scents، أوريجو سينتس، متجر عطور أصلية 100% في مصر يوفر عطورًا رجالية وعطورًا نسائية وعطورًا للجنسين من علامات موثوقة.",canonical:buildCanonicalUrl("/"),robots:"index,follow",jsonLd:buildHomepageStructuredData()};
  if(path==="/brands")return{title:"ماركات العطور الأصلية في مصر | ORIGO Scents",description:"تصفح ماركات العطور الأصلية المتوفرة لدى ORIGO Scents، وانتقل إلى صفحة كل علامة لاكتشاف منتجاتها وأسعارها.",canonical:buildCanonicalUrl("/brands"),robots:items.length?"index,follow":"noindex,follow",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"}])]};
  if(path.startsWith("/perfume/")){const product=productByPath(items,path);if(!product)return{title:"العطر غير موجود | ORIGO Scents",description:"",canonical:buildCanonicalUrl(path),robots:"noindex,follow",jsonLd:[]};const seo=buildProductSeo(product);return{...seo,ogType:"product",jsonLd:[buildProductStructuredData(product),buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:product.brandAr||product.brand,path:`/brands/${slug(product.brandEn||product.brand)}`},{name:product.nameAr||product.nameEn,path:productPath(product)}])]};}
  if(path==="/perfumes/original")return{title:"عطور أصلية 100% في مصر | ORIGO Scents - أوريجو سينتس",description:"تسوق عطورًا أصلية 100% للرجال والنساء وللجنسين من أشهر العلامات لدى ORIGO Scents، مع معرفة الأسعار والتوفر وخيارات التوصيل داخل مصر.",canonical:buildCanonicalUrl("/perfumes/original"),robots:items.length?"index,follow":"noindex,follow",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:"عطور أصلية",path:"/perfumes/original"}])]};
  const brandMatch=path.match(/^\/brands\/([^/]+)$/);if(brandMatch){const wanted=decodeURIComponent(brandMatch[1]),matches=items.filter(product=>brandRouteMatches(product,wanted)),sample=matches[0];if(!sample)return{title:"العلامة التجارية غير موجودة | ORIGO Scents",description:"",canonical:buildCanonicalUrl(path),robots:"noindex,follow",jsonLd:[]};const brand={ar:sample.brandAr,en:sample.brandEn||sample.brand,descriptionAr:sample.brandDescriptionAr,descriptionEn:sample.brandDescriptionEn},seo=buildBrandSeo(brand,matches.length,path),label=brand.ar||brand.en;return{...seo,jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"},{name:label,path}]),{"@context":"https://schema.org","@type":"CollectionPage",name:`عطور ${label} الأصلية`,url:seo.canonical,inLanguage:"ar-EG",mainEntity:{"@type":"ItemList",numberOfItems:matches.length,itemListElement:matches.map((product,index)=>({"@type":"ListItem",position:index+1,url:buildCanonicalUrl(productPath(product)),name:[...new Set([product.nameAr,product.nameEn].filter(Boolean))].join(" | ")}))}}]};}
  const categoryMatch=path.match(/^\/perfumes\/(men|women|unisex|edp|edt|winter|autumn|spring|summer|day|night)$/);if(categoryMatch){const key=categoryMatch[1],scoreKey=["winter","autumn","spring","summer"].includes(key)?"seasonScores":["day","night"].includes(key)?"usageTimeScores":null,matches=items.filter(product=>scoreKey?product[scoreKey]?.[key]!=null:key==="edp"||key==="edt"?String(product.concentration).toLowerCase()===key:product.gender===key),labels={men:"عطور رجالية أصلية",women:"عطور نسائية أصلية",unisex:"عطور أصلية للجنسين",edp:"عطور EDP أصلية",edt:"عطور EDT أصلية",winter:"عطور شتوية أصلية",autumn:"عطور خريفية أصلية",spring:"عطور ربيعية أصلية",summer:"عطور صيفية أصلية",day:"عطور نهارية أصلية",night:"عطور ليلية أصلية"};return{...buildCategorySeo(key,labels[key],matches.length),jsonLd:[]};}
  const noteMatch=path.match(/^\/notes\/([^/]+)$/);if(noteMatch){const key=noteMatch[1],matches=items.filter(product=>Object.values(product.noteSelectionsBundle||{}).flat().some(note=>[note?.ar,note?.en,note?.nameAr,note?.nameEn].some(name=>slug(name)===key)));return{title:`عطور ${key} الأصلية في مصر | ORIGO Scents`,description:`اكتشف العطور الأصلية التي تحتوي على نوتة ${key} والمتوفرة لدى ORIGO Scents.`,canonical:buildCanonicalUrl(path),robots:matches.length>=2?"index,follow":"noindex,follow",jsonLd:[]};}
  return{title:"العطور الأصلية في مصر | ORIGO Scents",description:"اكتشف العطور الأصلية للرجال والنساء وللجنسين في مصر من ORIGO Scents.",canonical:buildCanonicalUrl(path),robots:path==="/perfumes"?"index,follow":"noindex,follow",jsonLd:[]};
}

export function injectSeoIntoHtml(html,seo){
  const imageTags=seo.image?`<meta property="og:image" content="${esc(seo.image)}"><meta property="og:image:alt" content="${esc(seo.imageAlt||"")}"><meta name="twitter:image" content="${esc(seo.image)}">`:"";
  const tags=`<meta name="robots" content="${esc(seo.robots)}"><link rel="canonical" href="${esc(seo.canonical)}"><meta property="og:type" content="${esc(seo.ogType||"website")}"><meta property="og:site_name" content="${SITE_NAME}"><meta property="og:title" content="${esc(seo.title)}"><meta property="og:description" content="${esc(seo.description)}"><meta property="og:url" content="${esc(seo.canonical)}">${imageTags}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(seo.title)}"><meta name="twitter:description" content="${esc(seo.description)}">${list(seo.jsonLd).map(data=>`<script type="application/ld+json" data-origo-seo="${esc(data["@type"]||"entity")}">${JSON.stringify(data).replace(/</g,"\\u003c")}</script>`).join("")}`;
  const clean=html.replace(/<link\s+rel="canonical"[^>]*>/gi,"").replace(/<meta\s+(?:property="og:[^"]+"|name="twitter:[^"]+")[^>]*>/gi,"").replace(/<meta\s+name="robots"[^>]*>/gi,"").replace(/<script\s+type="application\/ld\+json"\s+data-origo-seo="[^"]+">[\s\S]*?<\/script>/gi,"");
  return clean.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(seo.title)}</title>`).replace(/<meta\s+name="description"[\s\S]*?>/i,`<meta name="description" content="${esc(seo.description)}">`).replace("</head>",`${tags}</head>`);
}

function productText(product){
  const notes=[...values(product.notesAr),...values(product.notesEn),...values(product.notes),...Object.values(product.noteSelectionsBundle||{}).flat()].map(item=>typeof item==="string"?item:item?.ar||item?.nameAr||item?.en||item?.nameEn).filter(Boolean);
  const accords=[...values(product.mainAccords),...values(product.accords),...values(product.accordProfile)].map(item=>typeof item==="string"?item:item?.ar||item?.nameAr||item?.en||item?.nameEn||item?.label).filter(Boolean);
  const fields=[["البراند",productBrand(product)],["التركيز",product.concentration],["الحجم",product.size||product.sizes?.[0]],["الجنس",({men:"رجالي",women:"نسائي",unisex:"للجنسين"})[product.gender]||product.gender],["السعر",money(product.price)],["التوفر",availableProduct(product)?"متوفر":"غير متوفر"]].filter(([,value])=>value!==undefined&&value!==null&&String(value).trim());
  const description=product.descriptionAr||product.descriptionEn||product.description||"";
  return `<dl class="pdp-seo-facts">${fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join("")}</dl>${description?`<section><h2>وصف العطر</h2><p>${esc(description)}</p></section>`:""}${notes.length?`<section><h2>النوتات العطرية</h2><p>${esc([...new Set(notes)].join("، "))}</p></section>`:""}${accords.length?`<section><h2>الأكوردات الرئيسية</h2><p>${esc([...new Set(accords)].join("، "))}</p></section>`:""}`;
}

function serverProductMarkup(product){
  const name=productName(product),brand=productBrand(product),path=productPath(product),photo=imageUrl(product),alt=buildImageAlt(product);
  return `<main class="pdp-page pdp-server-rendered" data-seo-rendered="product" aria-labelledby="product-dialog-title"><nav class="pdp-breadcrumb" aria-label="مسار الصفحة"><a href="/">الرئيسية</a><i>‹</i><a href="/perfumes">العطور</a><i>‹</i><a href="/brands/${encodeURIComponent(brandSlug(product))}">${esc(brand)}</a><i>‹</i><b>${esc(name)}</b></nav><section class="pdp-hero">${photo?`<div class="pdp-gallery"><div class="pdp-main-image"><img src="${esc(photo)}" alt="${esc(alt)}" width="800" height="900" loading="eager" fetchpriority="high" decoding="async"></div></div>`:""}<aside class="pdp-purchase"><a class="pdp-brand" href="/brands/${encodeURIComponent(brandSlug(product))}">${esc(brand)}</a><h1 id="product-dialog-title">${esc(name)}</h1><div class="pdp-price-row"><div class="pdp-price"><b>${esc(money(product.price))}</b></div></div><div class="pdp-stock ${availableProduct(product)?"available":"unavailable"}"><span>${availableProduct(product)?"متوفر للطلب":"غير متوفر حاليًا"}</span></div></aside></section>${productText(product)}<p class="sr-only"><a href="${esc(path)}">الرابط الدائم لـ ${esc(name)}</a></p></main>`;
}

function serverCardMarkup(product,index=0){const name=productName(product),brand=productBrand(product),photo=imageUrl(product),path=productPath(product);return `<article class="product-card origo-reference-product-card origo-exact-product-card" data-id="${esc(product.id)}" lang="ar" dir="rtl"><div class="product-image"><a class="product-card-media-link" href="${esc(path)}" aria-label="عرض ${esc(name)}">${photo?`<img src="${esc(photo)}" alt="${esc(buildImageAlt(product))}" width="640" height="700" loading="${index<2?"eager":"lazy"}" decoding="async">`:""}</a></div><div class="product-info"><div class="product-brand">${esc(brand)}</div><h2 class="exact-card-product-name"><a href="${esc(path)}">${esc(name)}</a></h2><div class="product-price"><b>${esc(money(product.price))}</b></div></div></article>`}

export function injectRouteContent(html,pathname,products=[]){
  const path=String(pathname||"/").replace(/\/$/,"")||"/",items=published(products);
  if(path==="/"){
    const brands=new Map();for(const product of items){const key=brandSlug(product);if(key&&!brands.has(key))brands.set(key,product)}
    const brandLinks=[...brands].map(([key,product])=>`<a class="marquee-item" href="/brands/${encodeURIComponent(key)}"><span>${esc(productBrand(product))}</span><b>${esc(productBrand(product))}</b></a>`).join("");
    const productLinks=items.slice(0,12).map(serverCardMarkup).join("");
    return html.replace('<div class="brand-carousel-track" id="home-brand-carousel-track" data-brand-marquee aria-live="off"></div>',`<div class="brand-carousel-track" id="home-brand-carousel-track" data-brand-marquee aria-live="off">${brandLinks}</div>`).replace('<div class="home-configured-product-rows" id="home-configured-product-rows" aria-live="polite"></div>',`<div class="home-configured-product-rows" id="home-configured-product-rows" aria-live="polite"><section class="home-brand-showcase"><div class="home-section-head"><h2>عطور أصلية مختارة</h2></div><div class="product-grid">${productLinks}</div></section></div>`);
  }
  if(path.startsWith("/perfume/")){const product=productByPath(items,path);if(!product)return html;return html.replace('<div id="product-dialog-content"></div>',`<div id="product-dialog-content">${serverProductMarkup(product)}</div>`).replace('class="overlay product-overlay" id="product-overlay" aria-hidden="true"','class="overlay product-overlay open" id="product-overlay" aria-hidden="false"');}
  if(path==="/brands"){
    const brands=new Map();for(const product of items){const key=brandSlug(product);if(key&&!brands.has(key))brands.set(key,product)}
    const content=`<nav class="brands-page-breadcrumb" aria-label="مسار الصفحة"><a href="/">الرئيسية</a><span>‹</span><b>العلامات التجارية</b></nav><header><span>دليل ORIGO</span><h1 id="brands-page-title">العلامات التجارية</h1><p>اختر العلامة لعرض جميع منتجاتها.</p></header><div class="brands-page-grid">${[...brands].map(([key,product])=>{const name=productBrand(product),initials=name.split(/\s+/).map(part=>part[0]).join("").slice(0,3).toUpperCase();return`<a href="/brands/${encodeURIComponent(key)}"><span>${esc(initials)}</span><b>${esc(name)}</b></a>`}).join("")}</div>`;
    return html.replace('id="brands-page" hidden','id="brands-page"').replace('<div class="brands-page-shell" id="brands-page-content"></div>',`<div class="brands-page-shell" id="brands-page-content">${content}</div>`).replace('<div class="origo-home" id="home">','<div class="origo-home" id="home" hidden>');
  }
  if(path==="/perfumes"||path==="/perfumes/original"||/^\/perfumes\/(?:men|women|unisex|edp|edt|winter|autumn|spring|summer|day|night)$/.test(path)||path.startsWith("/brands/")){
    let matches=items,title="العطور",intro="اكتشف العطور الأصلية المتوفرة لدى ORIGO Scents في مصر.";const brand=path.match(/^\/brands\/([^/]+)$/);if(brand){matches=items.filter(item=>brandRouteMatches(item,decodeURIComponent(brand[1])));title=matches[0]?`عطور ${productBrand(matches[0])} الأصلية`:"العلامة التجارية";intro=matches[0]?String(matches[0].brandDescriptionAr||matches[0].brandDescriptionEn||`تسوق عطور ${productBrand(matches[0])} الأصلية المتوفرة لدى ORIGO Scents في مصر.`):intro}
    const category=path.split("/")[2];if(!brand&&category&&category!=="original")matches=items.filter(product=>["edp","edt"].includes(category)?String(product.concentration).toLowerCase()===category:["men","women","unisex"].includes(category)?product.gender===category:["winter","autumn","spring","summer"].includes(category)?product.seasonScores?.[category]!=null:product.usageTimeScores?.[category]!=null);
    const grid=matches.map(serverCardMarkup).join("");return html.replace('id="catalog-page" hidden','id="catalog-page"').replace('<h1 id="catalog-title">العطور</h1>',`<h1 id="catalog-title">${esc(title)}</h1><p class="catalog-seo-intro">${esc(intro)}</p>`).replace('<div class="catalog-product-grid" id="catalog-product-grid" aria-live="polite"></div>',`<div class="catalog-product-grid" id="catalog-product-grid" aria-live="polite">${grid}</div>`).replace('<div class="origo-home" id="home">','<div class="origo-home" id="home" hidden>');
  }
  return html;
}

export function buildSitemap(products=[]){const items=published(products),urls=new Map([[buildCanonicalUrl("/"),null],[buildCanonicalUrl("/perfumes"),null]]);if(items.length){urls.set(buildCanonicalUrl("/perfumes/original"),null);urls.set(buildCanonicalUrl("/brands"),null)}for(const product of items){urls.set(buildCanonicalUrl(productPath(product)),product.updatedAt||product.updated_at||null);const currentBrandSlug=brandSlug(product);if(currentBrandSlug)urls.set(buildCanonicalUrl(`/brands/${currentBrandSlug}`),null);for(const key of ["winter","autumn","spring","summer"])if(product.seasonScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);for(const key of ["day","night"])if(product.usageTimeScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);if(["men","women","unisex"].includes(product.gender))urls.set(buildCanonicalUrl(`/perfumes/${product.gender}`),null);if(["edp","edt"].includes(String(product.concentration).toLowerCase()))urls.set(buildCanonicalUrl(`/perfumes/${String(product.concentration).toLowerCase()}`),null)}return`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(([loc,lastmod])=>`<url><loc>${esc(loc)}</loc>${lastmod?`<lastmod>${esc(String(lastmod).slice(0,10))}</lastmod>`:""}</url>`).join("")}</urlset>`}
export function robotsTxt(){return`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /account\nDisallow: /checkout\nDisallow: /cart\nDisallow: /search\nSitemap: ${SITE_URL}/sitemap.xml\n`}
