const SITE_URL="https://origoscents.com";
const SITE_NAME="ORIGO Scents";
const DEFAULT_SOCIAL_IMAGE=`${SITE_URL}/assets/origo-hero.png`;
const POLICY_URLS={shipping:`${SITE_URL}/policies/shipping`,returns:`${SITE_URL}/policies/returns`};
const BRAND_ALTERNATE_NAMES=["ORIGO","Origo Scents","أوريجو سينتس","أوريجو"];
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const slug=value=>String(value??"").normalize("NFKD").toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"");
const list=value=>Array.isArray(value)?value:[];
const published=products=>list(products).filter(product=>product?.status==="published"&&product.deleted!==true&&(product.category||"perfume")==="perfume");
const brandNames=product=>[...new Set([product?.brandAr,product?.brandEn,product?.brand].map(value=>String(value||"").trim()).filter(Boolean))];
const brandSlug=product=>slug(product?.brandSlug||product?.brandEn||product?.brand||product?.brandAr);
const brandRouteMatches=(product,wanted)=>brandNames(product).some(name=>slug(name)===wanted)||brandSlug(product)===wanted;
const money=value=>new Intl.NumberFormat("ar-EG",{style:"currency",currency:"EGP",maximumFractionDigits:2}).format(Number(value)||0);
const productName=product=>product?.nameAr||product?.nameEn||"";
const productBrand=product=>product?.brandAr||product?.brandEn||product?.brand||"";
const imageUrl=product=>list(product?.images).map(item=>typeof item==="string"?item:item?.url).find(Boolean)||product?.image||"";
const availableProduct=product=>product?.status!=="unavailable"&&(product?.inventory?.quantity==null||Number(product.inventory.quantity)>0);
const values=value=>Array.isArray(value)?value:value&&typeof value==="object"?[]:String(value||"").split(/[,،|]/).map(item=>item.trim()).filter(Boolean);
const compact=value=>String(value||"").replace(/\s+/g," ").trim();
const excerpt=(value,max=158)=>{const text=compact(value);if(text.length<=max)return text;const cut=text.slice(0,max-1),boundary=cut.lastIndexOf(" ");return`${cut.slice(0,boundary>max*.7?boundary:max-1).trim()}…`};

export function productPath(product){return `/perfume/${encodeURIComponent(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||product.id)}`}
export function buildCanonicalUrl(pathname="/"){const clean=`/${String(pathname).split("?")[0].replace(/^\/+|\/+$/g,"")}`;return `${SITE_URL}${clean==="/"?"/":clean}`}
export function buildImageAlt(product,language="ar"){const name=product.nameAr||product.nameEn||"عطر",brand=product.brandAr||product.brandEn||product.brand||"ORIGO Scents";return language==="ar"?`عطر ${name} من ${brand}`:`${product.nameEn||product.nameAr||"Perfume"} by ${product.brandEn||product.brandAr||product.brand||"ORIGO Scents"} perfume`}

function brandRecords(products=[],brandOptions=[]){
  const records=new Map();
  for(const option of list(brandOptions).filter(item=>item?.active!==false&&item?.metadata?.deleted!==true)){
    const key=slug(option.slug||option.nameEn||option.nameAr);if(!key)continue;
    records.set(key,{slug:key,nameAr:option.nameAr||"",nameEn:option.nameEn||"",image:option.image||"",descriptionAr:option.metadata?.descriptionAr||"",descriptionEn:option.metadata?.descriptionEn||"",updatedAt:option.updatedAt||null,products:[]});
  }
  for(const product of published(products)){
    const key=brandSlug(product);if(!key)continue;
    const current=records.get(key)||{slug:key,nameAr:"",nameEn:"",image:"",descriptionAr:"",descriptionEn:"",updatedAt:null,products:[]};
    current.nameAr=current.nameAr||product.brandAr||"";current.nameEn=current.nameEn||product.brandEn||product.brand||"";
    current.descriptionAr=current.descriptionAr||product.brandDescriptionAr||"";current.descriptionEn=current.descriptionEn||product.brandDescriptionEn||"";
    current.products.push(product);records.set(key,current);
  }
  return records;
}

export function buildProductSeo(product,language="ar"){
  const ar=language==="ar",name=ar?product.nameAr||product.nameEn:product.nameEn||product.nameAr,secondName=ar?product.nameEn:product.nameAr,brand=ar?product.brandAr||product.brandEn||product.brand:product.brandEn||product.brandAr||product.brand,size=product.size||product.sizes?.[0]||"",concentration=product.concentration||"",manual=product.seo||{};
  const fallbackTitle=ar?`عطر ${name} من ${brand} الأصلي في مصر | ORIGO Scents`:`${name} by ${brand} Original Perfume Egypt | ORIGO Scents`;
  const fallbackDescription=ar?`تسوق عطر ${name}${secondName&&secondName!==name?` (${secondName})`:""} الأصلي من ${brand} في مصر${size?`، ${size}`:""}${concentration?`، ${concentration}`:""}. تعرف على النوتات والسعر والتوفر لدى ORIGO Scents.`:`Shop original ${name}${secondName&&secondName!==name?` (${secondName})`:""} by ${brand} in Egypt${size?`, ${size}`:""}${concentration?`, ${concentration}`:""}. Explore notes, price and availability at ORIGO Scents.`;
  const image=list(product.images).map(item=>typeof item==="string"?item:item?.url).find(Boolean);
  return Object.freeze({title:manual.title||excerpt(fallbackTitle,68),description:manual.description||excerpt((ar?product.descriptionAr:product.descriptionEn)||fallbackDescription),canonical:buildCanonicalUrl(productPath(product)),robots:"index,follow",keywords:list(manual.keywords),image:image?new URL(image,SITE_URL).href:"",imageAlt:buildImageAlt(product,language)});
}

export function buildProductStructuredData(product){
  const seo=buildProductSeo(product),quantity=product.inventory?.quantity,available=product.status!=="unavailable"&&(quantity==null||Number(quantity)>0),images=list(product.images).map(image=>typeof image==="string"?image:image?.url).filter(Boolean).map(url=>new URL(url,SITE_URL).href),names=[...new Set([product.nameAr,product.nameEn].filter(Boolean))];
  const data={"@context":"https://schema.org","@type":"Product",name:names.join(" | "),description:seo.description,image:images,sku:product.sku||undefined,brand:{"@type":"Brand",name:product.brandAr||product.brandEn||product.brand},url:seo.canonical};
  const price=Number(product.price);if(Number.isFinite(price)&&price>=0)data.offers={"@type":"Offer",url:seo.canonical,priceCurrency:"EGP",price,availability:`https://schema.org/${available?"InStock":"OutOfStock"}`,itemCondition:"https://schema.org/NewCondition",hasMerchantReturnPolicy:{"@id":`${POLICY_URLS.returns}#policy`},shippingDetails:{"@type":"OfferShippingDetails",hasShippingService:{"@id":`${POLICY_URLS.shipping}#service`}}};
  if(/^\d{8,14}$/.test(String(product.barcode||"")))data.gtin=String(product.barcode);
  const internal=product.origoReviewSummary;
  const internalRating=Number(internal?.average),internalCount=Number(internal?.count);
  const verifiedInternal=internal?.source==="origo_customer_reviews"&&internal?.verified===true;
  if(verifiedInternal&&internalRating>0&&internalRating<=5&&Number.isInteger(internalCount)&&internalCount>0)data.aggregateRating={"@type":"AggregateRating",ratingValue:internalRating,reviewCount:internalCount};return data;
}

export function buildBreadcrumbStructuredData(items){return{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:buildCanonicalUrl(item.path)}))}}
function merchantReturnPolicy(){return{"@type":"MerchantReturnPolicy","@id":`${POLICY_URLS.returns}#policy`,url:POLICY_URLS.returns,applicableCountry:"EG",returnPolicyCountry:"EG",returnPolicyCategory:"https://schema.org/MerchantReturnFiniteReturnWindow",merchantReturnDays:7}}
function shippingService(){const period=(min,max)=>({"@type":"ServicePeriod",duration:{"@type":"QuantitativeValue",minValue:min,maxValue:max,unitCode:"DAY"}});return{"@type":"ShippingService","@id":`${POLICY_URLS.shipping}#service`,name:"ORIGO Scents delivery in Egypt",description:"Delivery times and charges are confirmed at checkout; charges vary by address and order.",fulfillmentType:"https://schema.org/FulfillmentTypeDelivery",shippingConditions:[{"@type":"ShippingConditions",shippingDestination:{"@type":"DefinedRegion",addressCountry:"EG"},transitTime:period(1,4)}]}}
export function buildHomepageStructuredData(){return[
  {"@context":"https://schema.org","@type":"WebSite","@id":`${SITE_URL}/#website`,url:`${SITE_URL}/`,name:SITE_NAME,alternateName:BRAND_ALTERNATE_NAMES,inLanguage:["ar-EG","en-EG"],publisher:{"@id":`${SITE_URL}/#organization`}},
  {"@context":"https://schema.org","@type":"Organization","@id":`${SITE_URL}/#organization`,url:`${SITE_URL}/`,name:SITE_NAME,alternateName:BRAND_ALTERNATE_NAMES,logo:{"@type":"ImageObject",url:`${SITE_URL}/assets/origo-logo.svg`},areaServed:{"@type":"Country",name:"Egypt"},hasMerchantReturnPolicy:merchantReturnPolicy(),hasShippingService:shippingService()}
]}
export function buildBrandSeo(brand,count,path=""){
  const ar=String(brand?.ar||brand?.nameAr||"").trim(),en=String(brand?.en||brand?.nameEn||brand?.name||brand||"").trim(),primary=ar||en,secondary=ar&&en&&ar!==en?en:"";
  const title=secondary?`عطور ${primary} الأصلية | ${secondary} Perfumes Egypt | ORIGO Scents`:`عطور ${primary} الأصلية في مصر | ORIGO Scents`;
  const savedDescription=String(brand?.descriptionAr||brand?.descriptionEn||brand?.description||"").trim();
  return{title,description:savedDescription||`تسوق عطور ${primary} الأصلية في مصر من ORIGO Scents. اكتشف ${count} ${count===1?"منتج":"منتجات"} متوفرة مع الأسعار وبيانات العطر وخيارات التوصيل.`,canonical:buildCanonicalUrl(path||`/brands/${slug(en||primary)}`),robots:count?"index,follow":"noindex,follow"};
}
export function buildCategorySeo(type,label,count){return{title:`${label} في مصر | ORIGO Scents`,description:`اكتشف ${label} المتوفرة فعليًا لدى ORIGO Scents مع الأسعار وبيانات العطر والتوصيل داخل مصر.`,canonical:buildCanonicalUrl(`/perfumes/${type}`),robots:count?"index,follow":"noindex,follow"}}
function productByPath(products,path){const wanted=decodeURIComponent(path.split("/").filter(Boolean)[1]||"");return published(products).find(product=>(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||String(product.id))===wanted)}
export function findProductForPath(products,path){return productByPath(products,path)}

export function seoForRoute(pathname,products=[],brandOptions=[]){
  const items=published(products),brands=brandRecords(items,brandOptions),path=String(pathname||"/").replace(/\/$/,"")||"/";
  if(["/search","/admin","/account","/checkout","/cart"].some(route=>path.startsWith(route))||path.startsWith("/fragrance-finder/results"))return{title:SITE_NAME,description:"",canonical:buildCanonicalUrl(path.startsWith("/search")?"/perfumes":path.startsWith("/fragrance-finder/results")?"/fragrance-finder/for-whom":path),robots:"noindex,follow",jsonLd:[]};
  if(path==="/")return{title:"ORIGO Scents | أوريجو سينتس - عطور أصلية 100% في مصر",description:"اكتشف ORIGO Scents، أوريجو سينتس، متجر عطور أصلية 100% في مصر يوفر عطورًا رجالية وعطورًا نسائية وعطورًا للجنسين من علامات موثوقة.",canonical:buildCanonicalUrl("/"),robots:"index,follow",jsonLd:buildHomepageStructuredData()};
  const policyMeta={
    "/policies/shipping":["سياسة الشحن والتوصيل – ORIGO Scents","تعرف على مدد التوصيل المتوقعة داخل مصر، معالجة الطلبات، رسوم الشحن والتتبع لدى ORIGO Scents."],
    "/policies/returns":["سياسة الإرجاع والاستبدال واسترداد الأموال – ORIGO Scents","تعرف على شروط إرجاع واستبدال واسترداد قيمة منتجات ORIGO Scents خلال 7 أيام وفق الشروط والقانون."],
    "/policies/privacy":["سياسة الخصوصية – ORIGO Scents","تعرف على كيفية استخدام ORIGO Scents لبيانات العملاء الضرورية للطلبات والتوصيل وخدمة العملاء."],
    "/policies/terms":["الشروط والأحكام – ORIGO Scents","اقرأ شروط الطلب والدفع والتوصيل والإلغاء واستخدام متجر ORIGO Scents داخل مصر."],
    "/about":["من نحن – ORIGO Scents | أوريجو سينتس","تعرف على ORIGO Scents، متجر العطور الأصلية المتخصص في مصر وتجربة اكتشاف العطور."],
    "/contact":["تواصل مع ORIGO Scents","تواصل مع ORIGO Scents عبر البريد الرسمي أو قنوات خدمة العملاء بشأن الطلبات والعطور."],
  };
  if(policyMeta[path]){const policyJson=path==="/policies/returns"?merchantReturnPolicy():path==="/policies/shipping"?shippingService():null;return{title:policyMeta[path][0],description:policyMeta[path][1],canonical:buildCanonicalUrl(path),robots:"index,follow",image:DEFAULT_SOCIAL_IMAGE,imageAlt:"ORIGO Scents",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:policyMeta[path][0],path}]),...(policyJson?[policyJson]:[])]};}
  if(path==="/brands")return{title:"ماركات العطور الأصلية في مصر | ORIGO Scents",description:"تصفح ماركات العطور الأصلية المتوفرة لدى ORIGO Scents، وانتقل إلى صفحة كل علامة لاكتشاف منتجاتها وأسعارها.",canonical:buildCanonicalUrl("/brands"),robots:items.length?"index,follow":"noindex,follow",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"}])]};
  if(path.startsWith("/perfume/")){const product=productByPath(items,path);if(!product)return{title:"العطر غير موجود | ORIGO Scents",description:"",canonical:buildCanonicalUrl(path),robots:"noindex,follow",jsonLd:[]};const seo=buildProductSeo(product);return{...seo,ogType:"product",jsonLd:[buildProductStructuredData(product),buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"},{name:productBrand(product),path:`/brands/${brandSlug(product)}`},{name:productName(product),path:productPath(product)}])]};}
  if(path==="/perfumes/original")return{title:"عطور أصلية 100% في مصر | ORIGO Scents - أوريجو سينتس",description:"تسوق عطورًا أصلية 100% للرجال والنساء وللجنسين من أشهر العلامات لدى ORIGO Scents، مع معرفة الأسعار والتوفر وخيارات التوصيل داخل مصر.",canonical:buildCanonicalUrl("/perfumes/original"),robots:items.length?"index,follow":"noindex,follow",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:"عطور أصلية",path:"/perfumes/original"}])]};
  const brandMatch=path.match(/^\/brands\/([^/]+)$/);if(brandMatch){const wanted=decodeURIComponent(brandMatch[1]),record=brands.get(wanted);if(!record)return{title:"العلامة التجارية غير موجودة | ORIGO Scents",description:"",canonical:buildCanonicalUrl(path),robots:"noindex,follow",jsonLd:[]};const brand={ar:record.nameAr,en:record.nameEn,descriptionAr:record.descriptionAr,descriptionEn:record.descriptionEn},seo=buildBrandSeo(brand,record.products.length,path),label=brand.ar||brand.en;return{...seo,jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"},{name:label,path}]),{"@context":"https://schema.org","@type":"CollectionPage",name:`عطور ${label} الأصلية`,url:seo.canonical,inLanguage:"ar-EG",mainEntity:{"@type":"ItemList",numberOfItems:record.products.length,itemListElement:record.products.map((product,index)=>({"@type":"ListItem",position:index+1,url:buildCanonicalUrl(productPath(product)),name:[...new Set([product.nameAr,product.nameEn].filter(Boolean))].join(" | ")}))}}]};}
  const categoryMatch=path.match(/^\/perfumes\/(men|women|unisex|edp|edt|winter|autumn|spring|summer|day|night)$/);if(categoryMatch){const key=categoryMatch[1],scoreKey=["winter","autumn","spring","summer"].includes(key)?"seasonScores":["day","night"].includes(key)?"usageTimeScores":null,matches=items.filter(product=>scoreKey?product[scoreKey]?.[key]!=null:key==="edp"||key==="edt"?String(product.concentration).toLowerCase()===key:product.gender===key),labels={men:"عطور رجالية أصلية",women:"عطور نسائية أصلية",unisex:"عطور أصلية للجنسين",edp:"عطور EDP أصلية",edt:"عطور EDT أصلية",winter:"عطور شتوية أصلية",autumn:"عطور خريفية أصلية",spring:"عطور ربيعية أصلية",summer:"عطور صيفية أصلية",day:"عطور نهارية أصلية",night:"عطور ليلية أصلية"},seo=buildCategorySeo(key,labels[key],matches.length);return{...seo,jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:labels[key],path:`/perfumes/${key}`}])]};}
  const noteMatch=path.match(/^\/notes\/([^/]+)$/);if(noteMatch){const key=noteMatch[1],matches=items.filter(product=>Object.values(product.noteSelectionsBundle||{}).flat().some(note=>[note?.ar,note?.en,note?.nameAr,note?.nameEn].some(name=>slug(name)===key)));return{title:`عطور ${key} الأصلية في مصر | ORIGO Scents`,description:`اكتشف العطور الأصلية التي تحتوي على نوتة ${key} والمتوفرة لدى ORIGO Scents.`,canonical:buildCanonicalUrl(path),robots:matches.length>=2?"index,follow":"noindex,follow",jsonLd:[]};}
  return{title:"العطور الأصلية في مصر | ORIGO Scents",description:"اكتشف العطور الأصلية للرجال والنساء وللجنسين في مصر من ORIGO Scents.",canonical:buildCanonicalUrl(path),robots:path==="/perfumes"?"index,follow":"noindex,follow",jsonLd:[]};
}

export function injectSeoIntoHtml(html,seo){
  const socialImage=seo.image||DEFAULT_SOCIAL_IMAGE,imageTags=`<meta property="og:image" content="${esc(socialImage)}"><meta property="og:image:alt" content="${esc(seo.imageAlt||SITE_NAME)}"><meta name="twitter:image" content="${esc(socialImage)}">`;
  const tags=`<meta name="robots" content="${esc(seo.robots)}"><link rel="canonical" href="${esc(seo.canonical)}"><meta property="og:type" content="${esc(seo.ogType||"website")}"><meta property="og:site_name" content="${SITE_NAME}"><meta property="og:title" content="${esc(seo.title)}"><meta property="og:description" content="${esc(seo.description)}"><meta property="og:url" content="${esc(seo.canonical)}">${imageTags}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(seo.title)}"><meta name="twitter:description" content="${esc(seo.description)}">${list(seo.jsonLd).map(data=>`<script type="application/ld+json" data-origo-seo="${esc(data["@type"]||"entity")}">${JSON.stringify(data).replace(/</g,"\\u003c")}</script>`).join("")}`;
  const clean=html.replace(/<link\s+rel="canonical"[^>]*>/gi,"").replace(/<meta\s+(?:property="og:[^"]+"|name="twitter:[^"]+")[^>]*>/gi,"").replace(/<meta\s+name="robots"[^>]*>/gi,"").replace(/<script\s+type="application\/ld\+json"\s+data-origo-seo="[^"]+">[\s\S]*?<\/script>/gi,"");
  return clean.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(seo.title)}</title>`).replace(/<meta\s+name="description"[\s\S]*?>/i,`<meta name="description" content="${esc(seo.description)}">`).replace("</head>",`${tags}</head>`);
}

function productText(product){
  const noteName=item=>typeof item==="string"?item:item?.ar||item?.nameAr||item?.en||item?.nameEn;
  const noteLayers=[["النوتات الافتتاحية",product.noteSelectionsBundle?.top],["نوتات القلب",product.noteSelectionsBundle?.heart],["النوتات الأساسية",product.noteSelectionsBundle?.base]].map(([label,items])=>[label,list(items).map(noteName).filter(Boolean)]).filter(([,items])=>items.length);
  const notes=[...values(product.notesAr),...values(product.notesEn),...values(product.notes)].map(noteName).filter(Boolean);
  const accords=[...values(product.mainAccords),...values(product.accords),...values(product.accordProfile)].map(item=>typeof item==="string"?item:item?.ar||item?.nameAr||item?.en||item?.nameEn||item?.label).filter(Boolean);
  const fields=[["البراند",productBrand(product)],["التركيز",product.concentration],["الحجم",product.size||product.sizes?.[0]],["الجنس",({men:"رجالي",women:"نسائي",unisex:"للجنسين"})[product.gender]||product.gender],["السعر",money(product.price)],["التوفر",availableProduct(product)?"متوفر":"غير متوفر"]].filter(([,value])=>value!==undefined&&value!==null&&String(value).trim());
  const description=product.descriptionAr||product.descriptionEn||product.description||"";
  return `<dl class="pdp-seo-facts">${fields.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value)}</dd></div>`).join("")}</dl>${description?`<section><h2>وصف العطر</h2><p>${esc(description)}</p></section>`:""}${noteLayers.map(([label,items])=>`<section><h2>${esc(label)}</h2><p>${esc([...new Set(items)].join("، "))}</p></section>`).join("")}${notes.length?`<section><h2>نوتات إضافية</h2><p>${esc([...new Set(notes)].join("، "))}</p></section>`:""}${accords.length?`<section><h2>الأكوردات الرئيسية</h2><p>${esc([...new Set(accords)].join("، "))}</p></section>`:""}`;
}

function serverProductMarkup(product){
  const name=productName(product),brand=productBrand(product),path=productPath(product),photo=imageUrl(product),alt=buildImageAlt(product);
  return `<main class="pdp-page pdp-server-rendered" data-seo-rendered="product" aria-labelledby="product-dialog-title"><nav class="pdp-breadcrumb" aria-label="مسار الصفحة"><a href="/">الرئيسية</a><i>‹</i><a href="/brands">العلامات التجارية</a><i>‹</i><a href="/brands/${encodeURIComponent(brandSlug(product))}">${esc(brand)}</a><i>‹</i><b>${esc(name)}</b></nav><section class="pdp-hero">${photo?`<div class="pdp-gallery"><div class="pdp-main-image"><img src="${esc(photo)}" alt="${esc(alt)}" width="800" height="900" loading="eager" fetchpriority="high" decoding="async"></div></div>`:""}<aside class="pdp-purchase"><a class="pdp-brand" href="/brands/${encodeURIComponent(brandSlug(product))}">${esc(brand)}</a><h1 id="product-dialog-title">${esc(name)}</h1><div class="pdp-price-row"><div class="pdp-price"><b>${esc(money(product.price))}</b></div></div><div class="pdp-stock ${availableProduct(product)?"available":"unavailable"}"><span>${availableProduct(product)?"متوفر للطلب":"غير متوفر حاليًا"}</span></div></aside></section>${productText(product)}<p class="sr-only"><a href="${esc(path)}">الرابط الدائم لـ ${esc(name)}</a></p></main>`;
}

function serverCardMarkup(product,index=0){const name=productName(product),brand=productBrand(product),photo=imageUrl(product),path=productPath(product);return `<article class="product-card origo-reference-product-card origo-exact-product-card" data-id="${esc(product.id)}" lang="ar" dir="rtl"><div class="product-image"><div class="product-card-top-actions" aria-hidden="true"></div><a class="product-card-media-link" href="${esc(path)}" aria-label="عرض ${esc(name)}">${photo?`<img src="${esc(photo)}" alt="${esc(buildImageAlt(product))}" width="640" height="700" loading="${index<2?"eager":"lazy"}" decoding="async">`:""}</a></div><div class="product-info"><div class="exact-card-heading"><div class="product-brand">${esc(brand)}</div></div><h3 class="exact-card-product-name"><a href="${esc(path)}">${esc(name)}</a></h3><div class="product-bottom"><div class="exact-card-prices"><b class="product-price">${esc(money(product.price))}</b></div><div class="exact-card-actions"><button class="card-add-button" type="button" data-action="add-to-cart" data-id="${esc(product.id)}" aria-label="إضافة ${esc(name)} إلى السلة">أضف للسلة</button></div></div></div></article>`}

export function injectRouteContent(html,pathname,products=[],brandOptions=[]){
  const path=String(pathname||"/").replace(/\/$/,"")||"/",items=published(products),brands=brandRecords(items,brandOptions);
  const policies={
    "/policies/shipping":{title:"سياسة الشحن والتوصيل",body:`<h1>سياسة الشحن والتوصيل</h1><p>في <strong>ORIGO Scents</strong> نحرص على وصول منتجاتك الأصلية بأمان وفي أسرع وقت ممكن.</p><h2>مدة التوصيل المتوقعة</h2><ul><li>القاهرة: من 1 إلى 2 يوم عمل.</li><li>الإسكندرية: من 1 إلى 2 يوم عمل.</li><li>باقي محافظات مصر: من 1 إلى 4 أيام عمل.</li></ul><p>هذه مدد تقديرية وقد تتأثر بالعطلات الرسمية أو ظروف شركات الشحن أو المناطق البعيدة.</p><h2>معالجة الطلبات</h2><p>الطلبات المكتملة قبل الساعة <strong>3:00 مساءً</strong> يمكن تجهيزها في يوم العمل نفسه، وما بعدها يبدأ التعامل معها في يوم العمل التالي.</p><h2>رسوم الشحن</h2><p>تختلف رسوم الشحن حسب العنوان والمحافظة وطبيعة الطلب، وتظهر الرسوم الفعلية أثناء إتمام الطلب وقبل تأكيد الشراء.</p><h2>التتبع والتأخير</h2><p>عند توفر رقم أو رابط تتبع من شركة الشحن نرسله عبر وسيلة التواصل المتاحة. وقد تحدث تأخيرات استثنائية بسبب العطلات أو ظروف شركة الشحن؛ تواصل معنا لمتابعة طلبك.</p>`},
    "/policies/returns":{title:"سياسة الإرجاع والاستبدال واسترداد الأموال",body:`<h1>سياسة الإرجاع والاستبدال واسترداد الأموال</h1><p>رضا عملائنا وثقتهم جزء أساسي من تجربة <strong>ORIGO Scents</strong>.</p><h2>مدة طلب الإرجاع</h2><p>يمكن طلب إرجاع المنتج خلال <strong>7 أيام من تاريخ استلام الطلب</strong>، وفق الشروط أدناه والقوانين المصرية واجبة التطبيق.</p><h2>حالة المنتج</h2><ul><li>في حالته الأصلية وغير مستخدم أو مفتوح.</li><li>الختم والتغليف الأصليان سليمين.</li><li>غير متضرر بسبب سوء الاستخدام.</li></ul><p>قد لا يكون المنتج مؤهلًا للإرجاع بعد فتح الختم أو الاستخدام، مع مراعاة الحقوق الإلزامية للمستهلك.</p><h2>المنتج الخطأ أو التالف</h2><p>إذا استلمت منتجًا مختلفًا أو تالفًا، تواصل مع خدمة عملاء ORIGO Scents في أقرب وقت لفحص الحالة واتخاذ الإجراء المناسب.</p><h2>تغيير الرأي والاسترداد</h2><p>قد يتحمل العميل تكاليف الشحن والإرجاع عند تغيير الرأي أو الاختيار الخاطئ، بالقدر الذي يسمح به القانون. بعد وصول المنتج وفحصه، تتم معالجة الاسترداد بالطريقة المناسبة وفق وسيلة الدفع.</p><h2>بدء الطلب</h2><p>ابدأ طلبك عبر <a href="mailto:support@origoscents.com">البريد الرسمي</a> أو <a href="/contact">صفحة التواصل</a> مع رقم الطلب وصور الحالة عند الحاجة.</p>`},
    "/policies/privacy":{title:"سياسة الخصوصية",body:`<h1>سياسة الخصوصية</h1><p>توضح هذه الصفحة كيف يتعامل <strong>ORIGO Scents</strong> مع البيانات اللازمة لتشغيل المتجر.</p><h2>البيانات التي قد نجمعها</h2><p>الاسم، رقم الهاتف، البريد الإلكتروني، عنوان التوصيل، بيانات الطلب، والمعلومات اللازمة لمعالجة الدفع والشحن، وبيانات تقنية مثل عنوان الشبكة ونوع الجهاز وسجلات الاستخدام وملفات تعريف الارتباط عند الاقتضاء.</p><h2>استخدام المعلومات والأساس</h2><p>نستخدم البيانات لتنفيذ الطلبات والتوصيل وخدمة العملاء وإدارة الحساب ومنع الاحتيال والوفاء بالالتزامات القانونية وتحسين المتجر. لا نرسل تواصلًا تسويقيًا إلا عندما يكون مسموحًا ويمكنك طلب إيقافه.</p><h2>مشاركة البيانات</h2><p>قد نشارك الحد اللازم مع شركات الشحن ومقدمي الدفع والاستضافة والتحليلات وخدمة العملاء، ولا نبيع بياناتك الشخصية.</p><h2>الاحتفاظ والحماية</h2><p>نحتفظ بالبيانات للمدة اللازمة لتنفيذ الطلب والالتزامات القانونية وتسوية النزاعات، ثم نحذفها أو نجعلها مجهلة متى لم تعد مطلوبة. نطبق ضوابط تقنية وتشغيلية مناسبة ونقصر الوصول على من يحتاجه.</p><h2>حقوقك واختياراتك</h2><p>يمكنك طلب الوصول إلى بياناتك أو تصحيحها أو حذفها أو الاعتراض على بعض أوجه استخدامها، مع مراعاة المتطلبات القانونية وسجلات المعاملات التي يلزم الاحتفاظ بها.</p><h2>ملفات تعريف الارتباط والخدمات الخارجية</h2><p>قد يستخدم المتجر ملفات ضرورية لتسجيل الجلسة والسلة والأمان، وأدوات قياس أو خدمات خارجية عند تفعيلها. يمكنك التحكم في الملفات غير الضرورية من إعدادات المتصفح أو أداة الموافقة المتاحة.</p><h2>التواصل والتحديثات</h2><p>لطلب متعلق بالخصوصية أو سحب موافقة تسويقية تواصل عبر <a href="mailto:support@origoscents.com">support@origoscents.com</a>. تاريخ آخر تحديث: 23 سبتمبر 2026.</p>`},
    "/policies/terms":{title:"الشروط والأحكام",body:`<h1>الشروط والأحكام</h1><p>باستخدام متجر <strong>ORIGO Scents</strong> أو تأكيد طلب، فإنك توافق على هذه الشروط والسياسات المرتبطة بها، مع بقاء حقوق المستهلك الإلزامية وفق القانون المصري.</p><h2>الطلبات والأسعار</h2><p>يعرض المتجر الأسعار بالجنيه المصري. إرسال الطلب لا يعني قبوله نهائيًا؛ يصبح الطلب مؤكدًا بعد التحقق من التوفر والبيانات والتواصل عند الحاجة. يجوز تصحيح الأخطاء الواضحة في السعر أو الوصف قبل التأكيد مع إتاحة الإلغاء للعميل.</p><h2>الدفع والتوصيل</h2><p>تظهر وسائل الدفع المتاحة ورسوم التوصيل قبل تأكيد الطلب. الدفع عند الاستلام، إن ظهر، يخضع للمنطقة وقيمة الطلب والتحقق. تخضع المدد والتكاليف لتفاصيل <a href="/policies/shipping">سياسة الشحن</a>.</p><h2>الإلغاء والإرجاع</h2><p>يمكن طلب إلغاء الطلب قبل تسليمه لشركة الشحن. بعد الشحن أو الاستلام تطبق <a href="/policies/returns">سياسة الإرجاع والاسترداد</a>، وقد لا تقبل المنتجات المفتوحة أو المستخدمة إلا عند وجود عيب أو حق قانوني واجب التطبيق.</p><h2>دقة بيانات العميل</h2><p>يتحمل العميل مسؤولية تقديم اسم وهاتف وعنوان صحيحين وقابلين للتواصل. قد يؤدي تعذر التواصل أو خطأ العنوان إلى تأخير أو إلغاء الطلب.</p><h2>المنتجات والمحتوى</h2><p>نبذل عناية معقولة لعرض الصور والأوصاف بدقة، وقد تختلف الألوان أو تفاصيل العبوة قليلًا بسبب الشاشة أو تحديثات الشركة المصنعة دون تغيير جوهر المنتج.</p><h2>الاستخدام المقبول والمسؤولية</h2><p>لا يجوز إساءة استخدام الموقع أو محاولة تعطيله أو الوصول غير المصرح به إليه. لا تستبعد هذه الشروط مسؤولية لا يجوز استبعادها قانونًا.</p><h2>التواصل والتحديثات</h2><p>للاستفسارات تواصل عبر <a href="mailto:support@origoscents.com">support@origoscents.com</a>. قد نحدّث هذه الشروط عند تغير الخدمة أو المتطلبات، وتطبق النسخة المنشورة وقت الطلب. تاريخ آخر تحديث: 23 سبتمبر 2026.</p>`},
    "/about":{title:"من نحن – ORIGO Scents",body:`<h1>ORIGO Scents</h1><h2>كل المنتجات أصلية</h2><p>في <strong>ORIGO Scents</strong> نؤمن أن شراء العطر يبدأ بالثقة. نقدم تجربة متخصصة تجمع العطور الأصلية مع المعلومات التي تساعدك على فهم العطر واختيار ما يناسب ذوقك في مصر.</p><h2>ما الذي يميز ORIGO؟</h2><ul><li>منتجات أصلية.</li><li>مجموعة واسعة ومتنامية من العطور والعلامات.</li><li>معلومات تفصيلية عن النوتات والأكوردات عند توفرها.</li><li>تجربة بحث واكتشاف تساعدك على اتخاذ قرار أفضل.</li><li>خدمة ودعم قبل وبعد الشراء.</li></ul><p>هدفنا بناء تجربة تساعدك على اكتشاف ذوقك العطري بثقة.</p>`},
    "/contact":{title:"تواصل مع ORIGO Scents",body:`<h1>تواصل مع ORIGO Scents</h1><p>للاستفسار عن العطور أو الطلبات أو الشحن والإرجاع، تواصل معنا عبر البريد الرسمي:</p><p><a href="mailto:support@origoscents.com">support@origoscents.com</a></p><p>يرجى إرفاق رقم الطلب عند متابعة طلب قائم، ولا ترسل كلمات المرور أو بيانات البطاقة الكاملة.</p>`}
  };
  if(policies[path]){const policy=policies[path],content=`<main id="storefront-main"><article class="origo-policy-page"><nav aria-label="مسار الصفحة"><a href="/">الرئيسية</a><span>‹</span><b>${esc(policy.title)}</b></nav>${policy.body}<footer><a href="/policies/shipping">الشحن والتوصيل</a><a href="/policies/returns">الإرجاع والاسترداد</a><a href="/policies/privacy">الخصوصية</a><a href="/policies/terms">الشروط والأحكام</a><a href="/about">من نحن</a><a href="/contact">تواصل معنا</a></footer></article></main>`;return html.replace(/<main id="storefront-main">[\s\S]*?<\/main>/,content)}
  if(path==="/"){
    const brandLinks=[...brands].filter(([,brand])=>brand.products.length).map(([key,brand])=>{const name=brand.nameAr||brand.nameEn,art=brand.image?`<img src="${esc(brand.image)}" alt="${esc(name)}" width="180" height="180" loading="lazy">`:`<span aria-hidden="true">${esc(name.slice(0,2).toUpperCase())}</span>`;return`<a class="brand-slider-card" href="/brands/${encodeURIComponent(key)}" aria-label="عرض منتجات ${esc(name)}">${art}</a>`}).join("");
    const productLinks=items.slice(0,12).map(serverCardMarkup).join("");
    return html.replace('<div class="brand-carousel-track" id="home-brand-carousel-track" data-brand-marquee aria-live="off"></div>',`<div class="brand-carousel-track" id="home-brand-carousel-track" data-brand-marquee aria-live="off">${brandLinks}</div>`).replace('<div class="home-configured-product-rows" id="home-configured-product-rows" aria-live="polite"></div>',`<div class="home-configured-product-rows" id="home-configured-product-rows" aria-live="polite" data-ssr-home-products><section class="home-configured-product-row" data-home-product-source="new"><div class="home-section-head"><a href="/perfumes?sort=newest">عرض الكل ‹</a><div class="ornament-heading"><h2>المنتجات الحديثة</h2></div></div><div class="home-products-wrap"><div class="product-grid home-product-row-track">${productLinks}</div></div></section></div>`);
  }
  if(path.startsWith("/perfume/")){const product=productByPath(items,path);if(!product)return html;return html.replace('<div id="product-dialog-content"></div>',`<div id="product-dialog-content">${serverProductMarkup(product)}</div>`).replace('class="overlay product-overlay" id="product-overlay" aria-hidden="true"','class="overlay product-overlay open" id="product-overlay" aria-hidden="false"');}
  if(path==="/brands"){
    const content=`<nav class="brands-page-breadcrumb" aria-label="مسار الصفحة"><a href="/">الرئيسية</a><span>‹</span><b>العلامات التجارية</b></nav><header><span>دليل ORIGO</span><h1 id="brands-page-title">العلامات التجارية</h1><p>اختر العلامة لعرض جميع منتجاتها.</p></header><div class="brands-page-grid">${[...brands].map(([key,brand])=>{const name=brand.nameAr||brand.nameEn,initials=name.split(/\s+/).map(part=>part[0]).join("").slice(0,3).toUpperCase();return`<a href="/brands/${encodeURIComponent(key)}"><span>${esc(initials)}</span><b>${esc(name)}</b></a>`}).join("")}</div>`;
    return html.replace('id="brands-page" hidden','id="brands-page"').replace('<div class="brands-page-shell" id="brands-page-content"></div>',`<div class="brands-page-shell" id="brands-page-content">${content}</div>`).replace('<div class="origo-home" id="home">','<div class="origo-home" id="home" hidden>');
  }
  if(path==="/perfumes"||path==="/perfumes/original"||/^\/perfumes\/(?:men|women|unisex|edp|edt|winter|autumn|spring|summer|day|night)$/.test(path)||path.startsWith("/brands/")){
    let matches=items,title="العطور",intro="اكتشف العطور الأصلية المتوفرة لدى ORIGO Scents في مصر.";const brand=path.match(/^\/brands\/([^/]+)$/);if(brand){const record=brands.get(decodeURIComponent(brand[1]));matches=record?.products||[];const label=record?.nameAr||record?.nameEn||"العلامة التجارية";title=record?`عطور ${label} الأصلية`:"العلامة التجارية";intro=record?String(record.descriptionAr||record.descriptionEn||`تسوق عطور ${label} الأصلية المتوفرة لدى ORIGO Scents في مصر.`):intro}
    const category=path.split("/")[2];if(!brand&&category&&category!=="original")matches=items.filter(product=>["edp","edt"].includes(category)?String(product.concentration).toLowerCase()===category:["men","women","unisex"].includes(category)?product.gender===category:["winter","autumn","spring","summer"].includes(category)?product.seasonScores?.[category]!=null:product.usageTimeScores?.[category]!=null);
    const grid=matches.map(serverCardMarkup).join(""),crumbs=brand?`<a href="/">الرئيسية</a><span>‹</span><a href="/brands">العلامات التجارية</a><span>‹</span><b>${esc(title.replace(/^عطور | الأصلية$/g,""))}</b>`:`<a href="/">الرئيسية</a><span>‹</span><b>${esc(title)}</b>`;return html.replace('id="catalog-page" hidden','id="catalog-page"').replace('<nav class="catalog-breadcrumb" id="catalog-breadcrumb" aria-label="مسار الصفحة"></nav>',`<nav class="catalog-breadcrumb" id="catalog-breadcrumb" aria-label="مسار الصفحة">${crumbs}</nav>`).replace('<h1 id="catalog-title">العطور</h1>',`<h1 id="catalog-title">${esc(title)}</h1><p class="catalog-seo-intro">${esc(intro)}</p>`).replace('<div class="catalog-product-grid" id="catalog-product-grid" aria-live="polite"></div>',`<div class="catalog-product-grid" id="catalog-product-grid" aria-live="polite">${grid}</div>`).replace('<div class="origo-home" id="home">','<div class="origo-home" id="home" hidden>');
  }
  return html;
}

export function buildSitemap(products=[],brandOptions=[]){const items=published(products),brands=brandRecords(items,brandOptions),urls=new Map([[buildCanonicalUrl("/"),null],[buildCanonicalUrl("/perfumes"),null]]);if(items.length){urls.set(buildCanonicalUrl("/perfumes/original"),null);urls.set(buildCanonicalUrl("/brands"),null)}for(const [key,brand] of brands)if(brand.products.length)urls.set(buildCanonicalUrl(`/brands/${key}`),brand.updatedAt);for(const product of items){urls.set(buildCanonicalUrl(productPath(product)),product.updatedAt||product.updated_at||null);for(const key of ["winter","autumn","spring","summer"])if(product.seasonScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);for(const key of ["day","night"])if(product.usageTimeScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);if(["men","women","unisex"].includes(product.gender))urls.set(buildCanonicalUrl(`/perfumes/${product.gender}`),null);if(["edp","edt"].includes(String(product.concentration).toLowerCase()))urls.set(buildCanonicalUrl(`/perfumes/${String(product.concentration).toLowerCase()}`),null)}return`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(([loc,lastmod])=>`<url><loc>${esc(loc)}</loc>${lastmod?`<lastmod>${esc(String(lastmod).slice(0,10))}</lastmod>`:""}</url>`).join("")}</urlset>`}
export function robotsTxt(){return`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /account\nDisallow: /checkout\nDisallow: /cart\nDisallow: /search\nSitemap: ${SITE_URL}/sitemap.xml\n`}
