const SITE_URL="https://origoscents.com";
const SITE_NAME="ORIGO Scents";
const BRAND_ALTERNATE_NAMES=["ORIGO","Origo Scents","Origo","ORIGO SCENTS","أوريجو سينتس","اوريجو سينتس","أوريجو","اوريجو","أوريغو","اوريغو"];
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const slug=value=>String(value??"").normalize("NFKD").toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,"-").replace(/^-+|-+$/g,"");
const list=value=>Array.isArray(value)?value:[];
const published=products=>list(products).filter(product=>product?.status==="published"&&product.deleted!==true&&(product.category||"perfume")==="perfume");
const brandNames=product=>[...new Set([product?.brandAr,product?.brandEn,product?.brand].map(value=>String(value||"").trim()).filter(Boolean))];
const brandSlug=product=>slug(product?.brandEn||product?.brand||product?.brandAr);
const brandRouteMatches=(product,wanted)=>brandNames(product).some(name=>slug(name)===wanted)||brandSlug(product)===wanted;

export function productPath(product){return `/perfume/${encodeURIComponent(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||product.id)}`}
export function buildCanonicalUrl(pathname="/"){const clean=`/${String(pathname).split("?")[0].replace(/^\/+|\/+$/g,"")}`;return `${SITE_URL}${clean==="/"?"/":clean}`}
export function buildImageAlt(product,language="ar"){return language==="ar"?`عطر ${product.nameAr||product.nameEn} من ${product.brandAr||product.brandEn||product.brand}`:`${product.nameEn||product.nameAr} by ${product.brandEn||product.brandAr||product.brand} perfume`}

export function buildProductSeo(product,language="ar"){
  const ar=language==="ar",name=ar?product.nameAr||product.nameEn:product.nameEn||product.nameAr,secondName=ar?product.nameEn:product.nameAr,brand=ar?product.brandAr||product.brandEn||product.brand:product.brandEn||product.brandAr||product.brand,size=product.size||product.sizes?.[0]||"",concentration=product.concentration||"",manual=product.seo||{};
  const bilingualName=secondName&&secondName!==name?`${name} | ${secondName}`:name;
  const fallbackTitle=ar?`${bilingualName} من ${brand}${size?` ${size}`:""} | عطر أصلي في مصر | ORIGO Scents`:`${brand} ${bilingualName}${size?` ${size}`:""} Original Perfume Egypt | ORIGO Scents`;
  const fallbackDescription=ar?`تسوق عطر ${name} الأصلي من ${brand} في مصر${size?`، ${size}`:""}${concentration?`، ${concentration}`:""}. تعرف على النوتات والثبات والفوحان والسعر والتوفر لدى ORIGO Scents.`:`Shop original ${name} by ${brand} in Egypt${size?`, ${size}`:""}${concentration?`, ${concentration}`:""}. Explore notes, longevity, projection, price and availability at ORIGO Scents.`;
  const image=list(product.images).map(item=>typeof item==="string"?item:item?.url).find(Boolean);
  return Object.freeze({title:manual.title||fallbackTitle,description:manual.description||(ar?product.descriptionAr:product.descriptionEn)||fallbackDescription,canonical:buildCanonicalUrl(productPath(product)),robots:"index,follow",keywords:list(manual.keywords),image:image?new URL(image,SITE_URL).href:"",imageAlt:buildImageAlt(product,language)});
}

export function buildProductStructuredData(product){
  const seo=buildProductSeo(product),quantity=product.inventory?.quantity,available=product.status!=="unavailable"&&(quantity==null||Number(quantity)>0),images=list(product.images).map(image=>typeof image==="string"?image:image?.url).filter(Boolean).map(url=>new URL(url,SITE_URL).href),names=[...new Set([product.nameAr,product.nameEn].filter(Boolean))];
  const data={"@context":"https://schema.org","@type":"Product",name:names.join(" | "),description:seo.description,image:images,sku:product.sku||undefined,brand:{"@type":"Brand",name:product.brandAr||product.brandEn||product.brand},offers:{"@type":"Offer",url:seo.canonical,priceCurrency:"EGP",price:Number(product.price),availability:`https://schema.org/${available?"InStock":"OutOfStock"}`,itemCondition:"https://schema.org/NewCondition"},url:seo.canonical};
  if(/^\d{8,14}$/.test(String(product.barcode||"")))data.gtin=String(product.barcode);
  const rating=Number(product.reviewSummary?.average??product.rating),count=Number(product.reviewSummary?.count);if(rating>0&&rating<=5&&count>0)data.aggregateRating={"@type":"AggregateRating",ratingValue:rating,reviewCount:count};return data;
}

export function buildBreadcrumbStructuredData(items){return{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:items.map((item,index)=>({"@type":"ListItem",position:index+1,name:item.name,item:buildCanonicalUrl(item.path)}))}}
export function buildHomepageStructuredData(){return[
  {"@context":"https://schema.org","@type":"WebSite","@id":`${SITE_URL}/#website`,url:`${SITE_URL}/`,name:SITE_NAME,alternateName:BRAND_ALTERNATE_NAMES,inLanguage:["ar-EG","en-EG"],publisher:{"@id":`${SITE_URL}/#organization`}},
  {"@context":"https://schema.org","@type":"Organization","@id":`${SITE_URL}/#organization`,url:`${SITE_URL}/`,name:SITE_NAME,legalName:"ORIGO",alternateName:BRAND_ALTERNATE_NAMES,logo:{"@type":"ImageObject",url:`${SITE_URL}/assets/origo-logo.svg`}}
]}
export function buildBrandSeo(brand,count,path=""){
  const ar=String(brand?.ar||brand?.nameAr||"").trim(),en=String(brand?.en||brand?.nameEn||brand?.name||brand||"").trim(),primary=ar||en,secondary=ar&&en&&ar!==en?en:"";
  const title=secondary?`عطور ${primary} الأصلية | ${secondary} Perfumes Egypt | ORIGO Scents`:`عطور ${primary} الأصلية في مصر | ORIGO Scents`;
  return{title,description:`تسوق عطور ${primary} الأصلية في مصر من ORIGO Scents. اكتشف المنتجات المتوفرة والأسعار والنوتات والثبات والفوحان والتوصيل داخل مصر.`,canonical:buildCanonicalUrl(path||`/brands/${slug(en||primary)}`),robots:count?"index,follow":"noindex,follow"};
}
export function buildCategorySeo(type,label,count){return{title:`${label} في مصر | ORIGO Scents`,description:`اكتشف ${label} المتوفرة فعليًا لدى ORIGO Scents مع الأسعار وبيانات العطر والتوصيل داخل مصر.`,canonical:buildCanonicalUrl(`/perfumes/${type}`),robots:count?"index,follow":"noindex,follow"}}
function productByPath(products,path){const wanted=decodeURIComponent(path.split("/").filter(Boolean)[1]||"");return published(products).find(product=>(product.slug||slug([product.brandEn||product.brand,product.nameEn||product.nameAr].filter(Boolean).join("-"))||String(product.id))===wanted)}

export function seoForRoute(pathname,products=[]){
  const items=published(products),path=String(pathname||"/").replace(/\/$/,"")||"/";
  if(["/search","/admin","/account","/checkout","/cart"].some(route=>path.startsWith(route))||path.startsWith("/fragrance-finder/results"))return{title:SITE_NAME,description:"",canonical:buildCanonicalUrl(path.startsWith("/search")?"/perfumes":path.startsWith("/fragrance-finder/results")?"/fragrance-finder/for-whom":path),robots:"noindex,follow",jsonLd:[]};
  if(path==="/")return{title:"ORIGO Scents | أوريجو سينتس - عطور أصلية 100% في مصر",description:"اكتشف ORIGO Scents، أوريجو سينتس، متجر عطور أصلية 100% في مصر يوفر عطورًا رجالية وعطورًا نسائية وعطورًا للجنسين من علامات موثوقة.",canonical:buildCanonicalUrl("/"),robots:"index,follow",jsonLd:buildHomepageStructuredData()};
  if(path.startsWith("/perfume/")){const product=productByPath(items,path);if(!product)return{title:"العطر غير موجود | ORIGO Scents",description:"",canonical:buildCanonicalUrl(path),robots:"noindex,follow",jsonLd:[]};const seo=buildProductSeo(product);return{...seo,jsonLd:[buildProductStructuredData(product),buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:product.brandAr||product.brand,path:`/brands/${slug(product.brandEn||product.brand)}`},{name:product.nameAr||product.nameEn,path:productPath(product)}])]};}
  if(path==="/perfumes/original")return{title:"عطور أصلية 100% في مصر | ORIGO Scents - أوريجو سينتس",description:"تسوق عطورًا أصلية 100% للرجال والنساء وللجنسين من أشهر العلامات لدى ORIGO Scents، مع معرفة الأسعار والتوفر وخيارات التوصيل داخل مصر.",canonical:buildCanonicalUrl("/perfumes/original"),robots:items.length?"index,follow":"noindex,follow",jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العطور",path:"/perfumes"},{name:"عطور أصلية",path:"/perfumes/original"}])]};
  const brandMatch=path.match(/^\/brands\/([^/]+)$/);if(brandMatch){const wanted=decodeURIComponent(brandMatch[1]),matches=items.filter(product=>brandRouteMatches(product,wanted)),sample=matches[0],brand={ar:sample?.brandAr,en:sample?.brandEn||sample?.brand||wanted},seo=buildBrandSeo(brand,matches.length,path),label=brand.ar||brand.en;return{...seo,jsonLd:[buildBreadcrumbStructuredData([{name:"الرئيسية",path:"/"},{name:"العلامات التجارية",path:"/brands"},{name:label,path}]),...matches.length?[{"@context":"https://schema.org","@type":"ItemList",name:`عطور ${label} الأصلية`,numberOfItems:matches.length,itemListElement:matches.map((product,index)=>({"@type":"ListItem",position:index+1,url:buildCanonicalUrl(productPath(product)),name:[...new Set([product.nameAr,product.nameEn].filter(Boolean))].join(" | ")}))}]:[]]};}
  const categoryMatch=path.match(/^\/perfumes\/(men|women|unisex|edp|edt|winter|autumn|spring|summer|day|night)$/);if(categoryMatch){const key=categoryMatch[1],scoreKey=["winter","autumn","spring","summer"].includes(key)?"seasonScores":["day","night"].includes(key)?"usageTimeScores":null,matches=items.filter(product=>scoreKey?product[scoreKey]?.[key]!=null:key==="edp"||key==="edt"?String(product.concentration).toLowerCase()===key:product.gender===key),labels={men:"عطور رجالية أصلية",women:"عطور نسائية أصلية",unisex:"عطور أصلية للجنسين",edp:"عطور EDP أصلية",edt:"عطور EDT أصلية",winter:"عطور شتوية أصلية",autumn:"عطور خريفية أصلية",spring:"عطور ربيعية أصلية",summer:"عطور صيفية أصلية",day:"عطور نهارية أصلية",night:"عطور ليلية أصلية"};return{...buildCategorySeo(key,labels[key],matches.length),jsonLd:[]};}
  const noteMatch=path.match(/^\/notes\/([^/]+)$/);if(noteMatch){const key=noteMatch[1],matches=items.filter(product=>Object.values(product.noteSelectionsBundle||{}).flat().some(note=>[note?.ar,note?.en,note?.nameAr,note?.nameEn].some(name=>slug(name)===key)));return{title:`عطور ${key} الأصلية في مصر | ORIGO Scents`,description:`اكتشف العطور الأصلية التي تحتوي على نوتة ${key} والمتوفرة لدى ORIGO Scents.`,canonical:buildCanonicalUrl(path),robots:matches.length>=2?"index,follow":"noindex,follow",jsonLd:[]};}
  return{title:"العطور الأصلية في مصر | ORIGO Scents",description:"اكتشف العطور الأصلية للرجال والنساء وللجنسين في مصر من ORIGO Scents.",canonical:buildCanonicalUrl(path),robots:path==="/perfumes"?"index,follow":"noindex,follow",jsonLd:[]};
}

export function injectSeoIntoHtml(html,seo){
  const imageTags=seo.image?`<meta property="og:image" content="${esc(seo.image)}"><meta property="og:image:alt" content="${esc(seo.imageAlt||"")}"><meta name="twitter:image" content="${esc(seo.image)}">`:"";
  const tags=`<meta name="robots" content="${esc(seo.robots)}"><link rel="canonical" href="${esc(seo.canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="${SITE_NAME}"><meta property="og:title" content="${esc(seo.title)}"><meta property="og:description" content="${esc(seo.description)}"><meta property="og:url" content="${esc(seo.canonical)}">${imageTags}<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${esc(seo.title)}"><meta name="twitter:description" content="${esc(seo.description)}">${list(seo.jsonLd).map(data=>`<script type="application/ld+json" data-origo-seo="${esc(data["@type"]||"entity")}">${JSON.stringify(data).replace(/</g,"\\u003c")}</script>`).join("")}`;
  const clean=html.replace(/<link\s+rel="canonical"[^>]*>/gi,"").replace(/<meta\s+(?:property="og:[^"]+"|name="twitter:[^"]+")[^>]*>/gi,"").replace(/<meta\s+name="robots"[^>]*>/gi,"").replace(/<script\s+type="application\/ld\+json"\s+data-origo-seo="[^"]+">[\s\S]*?<\/script>/gi,"");
  return clean.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(seo.title)}</title>`).replace(/<meta\s+name="description"[\s\S]*?>/i,`<meta name="description" content="${esc(seo.description)}">`).replace("</head>",`${tags}</head>`);
}

export function buildSitemap(products=[]){const items=published(products),urls=new Map([[buildCanonicalUrl("/"),null],[buildCanonicalUrl("/perfumes"),null]]);if(items.length)urls.set(buildCanonicalUrl("/perfumes/original"),null);for(const product of items){urls.set(buildCanonicalUrl(productPath(product)),product.updatedAt||product.updated_at||null);const currentBrandSlug=brandSlug(product);if(currentBrandSlug)urls.set(buildCanonicalUrl(`/brands/${currentBrandSlug}`),null);for(const key of ["winter","autumn","spring","summer"])if(product.seasonScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);for(const key of ["day","night"])if(product.usageTimeScores?.[key]!=null)urls.set(buildCanonicalUrl(`/perfumes/${key}`),null);if(["men","women","unisex"].includes(product.gender))urls.set(buildCanonicalUrl(`/perfumes/${product.gender}`),null);if(["edp","edt"].includes(String(product.concentration).toLowerCase()))urls.set(buildCanonicalUrl(`/perfumes/${String(product.concentration).toLowerCase()}`),null)}return`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[...urls].map(([loc,lastmod])=>`<url><loc>${esc(loc)}</loc>${lastmod?`<lastmod>${esc(String(lastmod).slice(0,10))}</lastmod>`:""}</url>`).join("")}</urlset>`}
export function robotsTxt(){return`User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /account\nDisallow: /checkout\nDisallow: /cart\nDisallow: /search\nSitemap: ${SITE_URL}/sitemap.xml\n`}
